// Copyright 2026 hha0x617
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "pch.h"
#include "Views/AboutDialog.xaml.h"
#if __has_include("AboutDialog.g.cpp")
#include "AboutDialog.g.cpp"
#endif
#include "GitVersion.h"

using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Controls;

// ============================================================================
// XAML template implementations (normally generated by XAML compiler Pass2;
// provided manually because the WinUI 3 NuGet does not wire Pass2 into the
// C++ native build chain)
// ============================================================================
namespace winrt::Em68030::implementation
{
    template <typename D, typename... I>
    void AboutDialogT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///Views/AboutDialog.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator);
        }
    }

    template <typename D, typename... I>
    void AboutDialogT<D, I...>::Connect(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        _contentLoaded = true;
    }

    template <typename D, typename... I>
    ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector
    AboutDialogT<D, I...>::GetBindingConnector(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        return nullptr;
    }

    template <typename D, typename... I>
    void AboutDialogT<D, I...>::UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const&)
    {
        throw ::winrt::hresult_not_implemented();
    }

    template <typename D, typename... I>
    void AboutDialogT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
    }
}

namespace winrt::Em68030::implementation
{
    AboutDialog::AboutDialog()
    {
        InitializeComponent();
        if (auto tb = FindName(L"BuildHashText").try_as<TextBlock>())
        {
            std::wstring text = L"Build: ";
            std::string hash = GIT_COMMIT_HASH;
            text.append(hash.begin(), hash.end());
            tb.Text(text);
        }
    }
}
