// Copyright 2026 hha0x617
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "pch.h"
#include "Views/ConsoleWindow.xaml.h"
#if __has_include("ConsoleWindow.g.cpp")
#include "ConsoleWindow.g.cpp"
#endif

#include "Helpers/ResourceHelper.h"
#include <microsoft.ui.xaml.window.h>
#include <commctrl.h>
#pragma comment(lib, "comctl32.lib")

using ::Em68030::ResourceHelper;
using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Input;
using namespace Microsoft::UI::Dispatching;
using namespace Microsoft::UI::Input;
using namespace Windows::System;
using namespace Windows::ApplicationModel::DataTransfer;

// Trim trailing whitespace from each line of terminal text for clipboard copy
static winrt::hstring TrimTrailingSpaces(winrt::hstring const& text)
{
    std::wstring result;
    result.reserve(text.size());
    size_t lineStart = 0;
    std::wstring_view sv{ text };
    while (lineStart <= sv.size())
    {
        auto pos = sv.find(L'\n', lineStart);
        auto lineEnd = (pos == std::wstring_view::npos) ? sv.size() : pos;
        auto line = sv.substr(lineStart, lineEnd - lineStart);
        // Remove trailing spaces/tabs
        auto trimEnd = line.find_last_not_of(L" \t");
        if (trimEnd != std::wstring_view::npos)
            result.append(line.data(), trimEnd + 1);
        // else: entirely blank line — append nothing (empty line)
        if (pos != std::wstring_view::npos)
            result += L'\n';
        else
            break;
        lineStart = pos + 1;
    }
    return winrt::hstring(result);
}

// Walk the visual tree to find a named child element (for TextBox template parts)
static DependencyObject FindChildByName(DependencyObject const& parent, hstring const& name)
{
    int count = Media::VisualTreeHelper::GetChildrenCount(parent);
    for (int i = 0; i < count; i++)
    {
        auto child = Media::VisualTreeHelper::GetChild(parent, i);
        if (auto fe = child.try_as<FrameworkElement>())
        {
            if (fe.Name() == name)
                return child;
        }
        auto result = FindChildByName(child, name);
        if (result != nullptr)
            return result;
    }
    return nullptr;
}

// ============================================================================
// XAML template implementations (normally generated by XAML compiler Pass2)
// ============================================================================
namespace winrt::Em68030::implementation
{
    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///Views/ConsoleWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator);
        }
    }

    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::Connect(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        _contentLoaded = true;
    }

    template <typename D, typename... I>
    ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector
    ConsoleWindowT<D, I...>::GetBindingConnector(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        return nullptr;
    }

    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const&)
    {
        throw ::winrt::hresult_not_implemented();
    }

    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
    }
}

namespace winrt::Em68030::implementation
{
    // Subclass proc — enforces minimum window size + focus-follows-mouse
    LRESULT CALLBACK ConsoleWindow::SubclassProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam,
                                                  UINT_PTR /*subclassId*/, DWORD_PTR refData)
    {
        if (msg == WM_GETMINMAXINFO)
        {
            auto* self = reinterpret_cast<ConsoleWindow*>(refData);
            auto* mmi = reinterpret_cast<MINMAXINFO*>(lParam);
            if (self->m_minWindowWidth > 0)
                mmi->ptMinTrackSize.x = self->m_minWindowWidth;
            if (self->m_minWindowHeight > 0)
                mmi->ptMinTrackSize.y = self->m_minWindowHeight;
            return 0;
        }
        if (msg == WM_NCDESTROY)
        {
            ::RemoveWindowSubclass(hwnd, SubclassProc, 1);
        }
        return ::DefSubclassProc(hwnd, msg, wParam, lParam);
    }

    ConsoleWindow::ConsoleWindow()
        : m_terminal(80, 24, 2000)
    {
        InitConsoleWindow();
    }

    ConsoleWindow::ConsoleWindow(int cols, int rows, int scrollbackLines)
        : m_terminal(cols, rows, scrollbackLines)
    {
        InitConsoleWindow();
    }

    void ConsoleWindow::InitConsoleWindow()
    {
        InitializeComponent();
        AppWindow().SetIcon(L"Assets/Em68030.ico");

        // Populate named elements via FindName on the Window's content tree
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            OutputBox(root.FindName(L"OutputBox").try_as<Microsoft::UI::Xaml::Controls::TextBox>());
        }

        // Wire event handlers programmatically (XAML Connect is no-op for C++ native)
        if (OutputBox())
        {
            OutputBox().PreviewKeyDown({ this, &ConsoleWindow::OutputBox_KeyDown });
            OutputBox().CharacterReceived({ this, &ConsoleWindow::OutputBox_CharacterReceived });

            // Custom context menu: Copy, Paste, Select All
            // (IsReadOnly TextBox doesn't show Paste in the default menu)
            auto menuFlyout = Microsoft::UI::Xaml::Controls::MenuFlyout();

            auto copyItem = Microsoft::UI::Xaml::Controls::MenuFlyoutItem();
            copyItem.Text(ResourceHelper::GetString(L"Context_Copy"));
            copyItem.KeyboardAcceleratorTextOverride(L"Ctrl+C");
            copyItem.Click([this](auto&&, auto&&) { OnContextCopy(); });
            menuFlyout.Items().Append(copyItem);

            auto pasteItem = Microsoft::UI::Xaml::Controls::MenuFlyoutItem();
            pasteItem.Text(ResourceHelper::GetString(L"Context_Paste"));
            pasteItem.KeyboardAcceleratorTextOverride(L"Ctrl+V");
            pasteItem.Click([this](auto&&, auto&&) { PasteFromClipboard(OnCharInput != nullptr); });
            menuFlyout.Items().Append(pasteItem);

            auto selectAllItem = Microsoft::UI::Xaml::Controls::MenuFlyoutItem();
            selectAllItem.Text(ResourceHelper::GetString(L"Context_SelectAll"));
            selectAllItem.KeyboardAcceleratorTextOverride(L"Ctrl+A");
            selectAllItem.Click([this](auto&&, auto&&) { OutputBox().SelectAll(); });
            menuFlyout.Items().Append(selectAllItem);

            OutputBox().ContextFlyout(menuFlyout);
        }
        // Focus-follows-mouse: activate window and focus OutputBox when pointer enters
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::UIElement>())
        {
            root.PointerEntered([this](auto&&, auto&&)
            {
                if (!m_hwnd)
                {
                    auto windowNative = this->try_as<::IWindowNative>();
                    if (windowNative)
                        windowNative->get_WindowHandle(&m_hwnd);
                }
                if (!m_hwnd || ::GetForegroundWindow() == m_hwnd)
                    return;
                // Bypass Windows foreground lock restriction by simulating Alt key
                ::keybd_event(VK_MENU, 0, KEYEVENTF_EXTENDEDKEY, 0);
                ::keybd_event(VK_MENU, 0, KEYEVENTF_EXTENDEDKEY | KEYEVENTF_KEYUP, 0);
                ::SetForegroundWindow(m_hwnd);
                Activate();
                if (OutputBox())
                    OutputBox().Focus(FocusState::Programmatic);
            });
        }

        // Wire search bar buttons
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            if (auto btn = root.FindName(L"SearchNextBtn").try_as<Controls::Button>())
                btn.Click([this](auto&&, auto&&) { FindNext(); });
            if (auto btn = root.FindName(L"SearchPrevBtn").try_as<Controls::Button>())
                btn.Click([this](auto&&, auto&&) { FindPrev(); });
            if (auto btn = root.FindName(L"SearchCloseBtn").try_as<Controls::Button>())
                btn.Click([this](auto&&, auto&&) { CloseSearch(); });
            if (auto box = root.FindName(L"SearchBox").try_as<Controls::TextBox>())
            {
                box.KeyDown([this](auto&&, KeyRoutedEventArgs const& e)
                {
                    if (e.Key() == VirtualKey::Enter)
                    {
                        FindNext();
                        e.Handled(true);
                    }
                    else if (e.Key() == VirtualKey::Escape)
                    {
                        CloseSearch();
                        e.Handled(true);
                    }
                    else if (e.Key() == VirtualKey::F3)
                    {
                        auto shiftState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Shift);
                        bool shiftDown = (shiftState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                                         Windows::UI::Core::CoreVirtualKeyStates::Down;
                        if (shiftDown) FindPrev(); else FindNext();
                        e.Handled(true);
                    }
                });
            }
        }

        UpdateTitle();
        AppWindow().Resize({ 700, 510 });

        // Create a DispatcherQueueTimer for 100ms render updates.
        // This is the WinUI 3 equivalent of WPF's DispatcherTimer.
        auto dispatcherQueue = DispatcherQueue();
        m_renderTimer = dispatcherQueue.CreateTimer();
        m_renderTimer.Interval(std::chrono::milliseconds(100));
        m_renderTimerToken = m_renderTimer.Tick([this](auto&&, auto&&)
        {
            RenderScreen();
        });
        m_renderTimer.Start();

        // Focus the output TextBox for keyboard capture
        // Use Loaded event for reliable initial focus (Activated can fire before content is ready)
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            root.Loaded([this](auto&&, auto&&)
            {
                if (OutputBox())
                {
                    OutputBox().Focus(FocusState::Programmatic);
                    MeasureCharCell();
                }
            });

            // SizeChanged for dynamic terminal resize
            root.SizeChanged({ this, &ConsoleWindow::OnSizeChanged });
        }
        // Also re-focus on window re-activation
        Activated([this](auto&&, Microsoft::UI::Xaml::WindowActivatedEventArgs const& args)
        {
            if (args.WindowActivationState() != Microsoft::UI::Xaml::WindowActivationState::Deactivated)
            {
                if (OutputBox())
                    OutputBox().Focus(FocusState::Programmatic);
            }
        });



        // Stop render timer when window is closed (prevents accessing dead UI)
        Closed([this](auto&&, auto&&)
        {
            if (m_renderTimer)
            {
                m_renderTimer.Stop();
                m_renderTimer = nullptr;
            }
        });
    }

    // ========================================================================
    // Scrollback resize (called from UI thread)
    // ========================================================================

    void ConsoleWindow::SetScrollbackLines(int lines)
    {
        m_terminal.ResizeScrollback(lines);
    }

    void ConsoleWindow::SetTerminalSize(int cols, int rows)
    {
        cols = std::max(cols, 80);
        rows = std::max(rows, 24);
        if (cols == m_terminal.GetCols() && rows == m_terminal.GetRows()) return;

        m_terminal.Resize(cols, rows);
        UpdateTitle();

        // Adjust window size to fit the new terminal dimensions.
        // AppWindow().Size() is in physical pixels; XAML layout values are in DIPs.
        // Must convert via RasterizationScale to avoid size mismatch at non-100% DPI.
        if (m_charMeasured && m_charWidth > 0 && m_charHeight > 0)
        {
            auto appWindow = AppWindow();
            auto currentSize = appWindow.Size();
            float scale = static_cast<float>(OutputBox().XamlRoot().RasterizationScale());

            float windowWidthDip = static_cast<float>(currentSize.Width) / scale;
            float windowHeightDip = static_cast<float>(currentSize.Height) / scale;

            float textAreaHeight;
            if (m_contentScrollViewer)
                textAreaHeight = static_cast<float>(m_contentScrollViewer.ActualHeight()) - m_textAreaOverhead;
            else
                textAreaHeight = static_cast<float>(OutputBox().ActualHeight()) - 8;
            float textW = static_cast<float>(OutputBox().ActualWidth()) - 8; // Padding="4" x2
            float chromeW = windowWidthDip - textW;
            float chromeH = windowHeightDip - textAreaHeight;

            int newWidth = static_cast<int>((cols * m_charWidth + chromeW) * scale + 0.5f);
            int newHeight = static_cast<int>((rows * m_charHeight + chromeH) * scale + 0.5f);
            appWindow.Resize({ newWidth, newHeight });
        }
    }

    void ConsoleWindow::MeasureCharCell()
    {
        // Measure char width and line step from a multi-line TextBlock.
        // Single-line TextBlock.DesiredSize().Height includes internal top/bottom
        // margins that are NOT repeated per additional line. Using a single-line
        // height as "charHeight" overestimates each line by that margin, causing
        // proportional error: +1 line at 24 rows, +4 lines at 52 rows.
        // Multi-line differencing gives the pure line step.
        auto tb = Microsoft::UI::Xaml::Controls::TextBlock();
        tb.FontFamily(OutputBox().FontFamily());
        tb.FontSize(OutputBox().FontSize());
        tb.TextWrapping(Microsoft::UI::Xaml::TextWrapping::NoWrap);

        const int n1 = 10, n2 = 20;
        constexpr float inf = std::numeric_limits<float>::infinity();
        std::wstring text1, text2;
        for (int i = 0; i < n2; i++)
        {
            if (i > 0) text2 += L'\n';
            text2 += L'M';
            if (i < n1)
            {
                if (i > 0) text1 += L'\n';
                text1 += L'M';
            }
        }

        tb.Text(L"M");
        tb.Measure({ inf, inf });
        m_charWidth = tb.DesiredSize().Width;

        tb.Text(text1);
        tb.Measure({ inf, inf });
        float h10 = tb.DesiredSize().Height;

        tb.Text(text2);
        tb.Measure({ inf, inf });
        float h20 = tb.DesiredSize().Height;

        m_charHeight = (h20 - h10) / static_cast<float>(n2 - n1);

        // Cache the ContentElement (ScrollViewer) inside the TextBox template.
        auto contentObj = FindChildByName(OutputBox(), L"ContentElement");
        m_contentScrollViewer = contentObj.try_as<Controls::ScrollViewer>();

        // Subscribe to ViewChanged for sticky auto-scroll tracking
        if (m_contentScrollViewer)
        {
            m_contentScrollViewer.ViewChanged([this](auto&&, Controls::ScrollViewerViewChangedEventArgs const&)
            {
                if (m_suppressScrollEvent) return;
                double offset = m_contentScrollViewer.VerticalOffset();
                double viewportHeight = m_contentScrollViewer.ViewportHeight();
                double extentHeight = m_contentScrollViewer.ExtentHeight();
                // Threshold: one line height to account for TextWrapping layout changes
                double threshold = m_charHeight > 0 ? m_charHeight : 20;
                bool atBottom = (offset + viewportHeight >= extentHeight - threshold);

                if (m_autoScroll)
                {
                    // Only turn off auto-scroll when user explicitly scrolls away from bottom
                    if (!atBottom)
                        m_autoScroll = false;
                }
                else
                {
                    // Turn auto-scroll back on when user scrolls to the bottom
                    if (atBottom)
                    {
                        m_autoScroll = true;
                        m_terminal.SetDirty();
                    }
                }
            });
        }

        // The overhead is the constant vertical space inside the TextBox content
        // area that isn't text lines (padding, borders, etc.).
        // TextBox Padding="4" → 4 top + 4 bottom = 8 DIPs.
        m_textAreaOverhead = 8;

        // Compute chrome (non-text-area portion of window) in DIPs.
        // AppWindow().Size() is in physical pixels — convert to DIPs via RasterizationScale.
        auto currentSize = AppWindow().Size();
        float scale = static_cast<float>(OutputBox().XamlRoot().RasterizationScale());
        float windowWidthDip = static_cast<float>(currentSize.Width) / scale;
        float windowHeightDip = static_cast<float>(currentSize.Height) / scale;

        float textAreaHeight;
        if (m_contentScrollViewer)
            textAreaHeight = static_cast<float>(m_contentScrollViewer.ActualHeight()) - m_textAreaOverhead;
        else
            textAreaHeight = static_cast<float>(OutputBox().ActualHeight()) - 8;
        float textAreaWidth;
        textAreaWidth = static_cast<float>(OutputBox().ActualWidth()) - 8; // Padding="4" x2
        float chromeW = windowWidthDip - textAreaWidth;
        float chromeH = windowHeightDip - textAreaHeight;

        // WM_GETMINMAXINFO uses physical pixels
        m_minWindowWidth = static_cast<int>((80 * m_charWidth + chromeW) * scale + 0.5f);
        m_minWindowHeight = static_cast<int>((24 * m_charHeight + chromeH) * scale + 0.5f);

        // Install Win32 subclass to handle WM_GETMINMAXINFO for minimum size
        if (!m_hwnd)
        {
            auto windowNative = this->try_as<::IWindowNative>();
            if (windowNative)
            {
                windowNative->get_WindowHandle(&m_hwnd);
                if (m_hwnd)
                    ::SetWindowSubclass(m_hwnd, SubclassProc, 1, reinterpret_cast<DWORD_PTR>(this));
            }
        }

        m_charMeasured = true;

        // Resize window to fit the configured terminal dimensions.
        // The constructor uses a temporary default size; now that we know the
        // actual char cell size, set the correct window size.
        {
            int cols = m_terminal.GetCols();
            int rows = m_terminal.GetRows();
            int newWidth = static_cast<int>((cols * m_charWidth + chromeW) * scale + 0.5f);
            int newHeight = static_cast<int>((rows * m_charHeight + chromeH) * scale + 0.5f);
            AppWindow().Resize({ newWidth, newHeight });
        }
    }

    void ConsoleWindow::UpdateTitle()
    {
        Title(winrt::hstring(ResourceHelper::Format(L"Window_ConsoleFormat",
            m_terminal.GetCols(), m_terminal.GetRows())));
    }

    void ConsoleWindow::OnSizeChanged([[maybe_unused]] IInspectable const& sender,
                                       SizeChangedEventArgs const& /*e*/)
    {
        if (!m_charMeasured || m_charWidth <= 0 || m_charHeight <= 0) return;
        if (!OutputBox()) return;

        // Use the ContentElement (ScrollViewer inside the TextBox) for accurate
        // text area measurement — OutputBox().ActualHeight() includes WinUI3
        // TextBox template chrome (border, header row, etc.) that adds ~3 rows
        // of phantom height. m_textAreaOverhead is measured empirically.
        float availableWidth;
        float availableHeight;
        if (m_contentScrollViewer)
        {
            // Use ScrollViewer viewport for accurate text area (excludes scrollbar)
            availableWidth = static_cast<float>(OutputBox().ActualWidth()) - 8; // Padding="4" x2
            availableHeight = static_cast<float>(m_contentScrollViewer.ActualHeight()) - m_textAreaOverhead;
        }
        else
        {
            availableWidth = static_cast<float>(OutputBox().ActualWidth()) - 8;
            availableHeight = static_cast<float>(OutputBox().ActualHeight()) - 8;
        }

        if (availableWidth <= 0 || availableHeight <= 0) return;

        int newCols = std::max(80, static_cast<int>(availableWidth / m_charWidth));
        int newRows = std::max(24, static_cast<int>(availableHeight / m_charHeight));

        if (newCols != m_terminal.GetCols() || newRows != m_terminal.GetRows())
        {
            m_terminal.Resize(newCols, newRows);
            UpdateTitle();
        }
    }

    // Thread-safe output (called from emulation thread)
    // ========================================================================

    void ConsoleWindow::AppendChar(char ch)
    {
        std::lock_guard lock(m_outputMutex);
        m_outputQueue.push(ch);
    }

    void ConsoleWindow::AppendString(const std::string& s)
    {
        std::lock_guard lock(m_outputMutex);
        for (char ch : s)
            m_outputQueue.push(ch);
    }

    // ========================================================================
    // Thread-safe input (called from emulation thread)
    // ========================================================================

    char ConsoleWindow::ReadChar()
    {
        std::lock_guard lock(m_inputMutex);
        if (!m_charBuffer.empty())
        {
            char ch = m_charBuffer.front();
            m_charBuffer.pop();
            return ch;
        }
        return '\0';
    }

    std::string ConsoleWindow::ReadString()
    {
        std::lock_guard lock(m_inputMutex);
        if (!m_lineBuffer.empty())
        {
            std::string line = m_lineBuffer.front();
            m_lineBuffer.pop();
            return line;
        }
        return "";
    }

    // ========================================================================
    // Render timer callback
    // ========================================================================

    void ConsoleWindow::RenderScreen()
    {
        // Drain output queue into the VT100 terminal emulator.
        // Always drain, even if we skip the UI update, so the terminal
        // state stays current.
        {
            std::lock_guard lock(m_outputMutex);
            while (!m_outputQueue.empty())
            {
                m_terminal.Write(m_outputQueue.front());
                m_outputQueue.pop();
            }
        }

        // Cursor blink: toggle every 5 ticks (500ms on, 500ms off at 100ms interval)
        m_blinkCounter++;
        bool newVisible = (m_blinkCounter / 5) % 2 == 0;
        bool blinkChanged = newVisible != m_cursorVisible;
        m_cursorVisible = newVisible;

        if (!m_terminal.IsDirty() && !blinkChanged)
            return;

        // Suspend text updates while the user has a text selection active,
        // so mouse-drag selections aren't reset every 100ms render tick.
        if (OutputBox().SelectionLength() > 0)
            return;

        // Skip text updates while scrolled back — the terminal continues
        // processing output internally, and will render when user scrolls
        // back to bottom (m_autoScroll becomes true via ViewChanged event).
        if (!m_autoScroll)
        {
            m_terminal.ClearDirty();
            return;
        }

        // Skip if the previous render's UI update hasn't completed yet.
        // The terminal stays dirty so the next timer tick will retry.
        if (m_rendering)
            return;

        m_terminal.ClearDirty();
        m_rendering = true;
        m_suppressScrollEvent = true;

        std::string rendered = m_cursorVisible
            ? m_terminal.RenderFullWithCursor()
            : m_terminal.RenderFull();

        OutputBox().Text(winrt::to_hstring(rendered));

        // Use Select(end, 0) to move caret to end — this works WITH the
        // TextBox's internal "scroll to caret" mechanism to auto-scroll.
        auto textLength = OutputBox().Text().size();
        OutputBox().Select(static_cast<int32_t>(textLength), 0);

        // Clear flags after layout settles (deferred to avoid
        // catching internal scroll events triggered by the text update)
        DispatcherQueue().TryEnqueue(
            Microsoft::UI::Dispatching::DispatcherQueuePriority::Low,
            [this]()
            {
                m_suppressScrollEvent = false;
                m_rendering = false;
            });
    }

    // ========================================================================
    // Keyboard input handling
    // ========================================================================

    void ConsoleWindow::OutputBox_KeyDown([[maybe_unused]] IInspectable const& sender,
                                         KeyRoutedEventArgs const& e)
    {
        auto key = e.Key();

        // Ctrl+Shift+F: open search bar (works in all modes)
        {
            auto ctrlState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Control);
            auto shiftState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Shift);
            bool ctrlDown = (ctrlState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                            Windows::UI::Core::CoreVirtualKeyStates::Down;
            bool shiftDown = (shiftState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                             Windows::UI::Core::CoreVirtualKeyStates::Down;
            if (ctrlDown && shiftDown && key == VirtualKey::F)
            {
                OpenSearch();
                e.Handled(true);
                return;
            }
        }

        // Search mode: intercept F3/Shift+F3 and Escape
        if (m_searchMode)
        {
            if (key == VirtualKey::F3)
            {
                auto shiftState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Shift);
                bool shiftDown = (shiftState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                                 Windows::UI::Core::CoreVirtualKeyStates::Down;
                if (shiftDown) FindPrev(); else FindNext();
                e.Handled(true);
                return;
            }
            if (key == VirtualKey::Escape)
            {
                CloseSearch();
                e.Handled(true);
                return;
            }
        }

        if (OnCharInput)
        {
            // MVME147 mode: send VT100 sequences for special keys
            // Arrow keys use ESC O x in application mode (DECCKM), ESC [ x in normal mode
            std::string arrow = m_terminal.GetApplicationCursorKeys() ? "\x1BO" : "\x1B[";
            std::string seq;

            switch (key)
            {
            case VirtualKey::Enter:    seq = "\r"; break;
            case VirtualKey::Up:       seq = arrow + "A"; break;
            case VirtualKey::Down:     seq = arrow + "B"; break;
            case VirtualKey::Left:     seq = arrow + "D"; break;
            case VirtualKey::Right:    seq = arrow + "C"; break;
            case VirtualKey::Home:     seq = "\x1B[H"; break;
            case VirtualKey::End:      seq = "\x1B[F"; break;
            case VirtualKey::Back:     seq = "\x7F"; break;
            case VirtualKey::Delete:   seq = "\x1B[3~"; break;
            case VirtualKey::Tab:      seq = "\t"; break;
            case VirtualKey::Escape:   seq = "\x1B"; break;
            case VirtualKey::PageUp:   seq = "\x1B[5~"; break;
            case VirtualKey::PageDown: seq = "\x1B[6~"; break;
            case VirtualKey::Insert:   seq = "\x1B[2~"; break;
            case VirtualKey::F1:       seq = "\x1BOP"; break;
            case VirtualKey::F2:       seq = "\x1BOQ"; break;
            case VirtualKey::F3:       seq = "\x1BOR"; break;
            case VirtualKey::F4:       seq = "\x1BOS"; break;
            case VirtualKey::F5:       seq = "\x1B[15~"; break;
            case VirtualKey::F6:       seq = "\x1B[17~"; break;
            case VirtualKey::F7:       seq = "\x1B[18~"; break;
            case VirtualKey::F8:       seq = "\x1B[19~"; break;
            case VirtualKey::F9:       seq = "\x1B[20~"; break;
            case VirtualKey::F10:      seq = "\x1B[21~"; break;
            case VirtualKey::F11:      seq = "\x1B[23~"; break;
            case VirtualKey::F12:      seq = "\x1B[24~"; break;
            default: break;
            }

            if (!seq.empty())
            {
                SendRawBytes(seq);
                e.Handled(true);
                return;
            }

            // Ctrl key state (used for Ctrl+C, Ctrl+V, Ctrl+A..Z)
            auto ctrlState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Control);
            bool ctrlDown = (ctrlState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                            Windows::UI::Core::CoreVirtualKeyStates::Down;

            // Ctrl+C: copy selected text, or send 0x03 (ETX) if no selection
            if (ctrlDown && key == VirtualKey::C)
            {
                if (OutputBox().SelectionLength() > 0)
                {
                    Windows::ApplicationModel::DataTransfer::DataPackage dp;
                    dp.SetText(TrimTrailingSpaces(OutputBox().SelectedText()));
                    Windows::ApplicationModel::DataTransfer::Clipboard::SetContent(dp);
                    OutputBox().Select(OutputBox().SelectionStart(), 0);
                }
                else
                {
                    OnCharInput(0x03);
                }
                e.Handled(true);
                return;
            }

            // Ctrl+V: paste clipboard text into SCC
            if (ctrlDown && key == VirtualKey::V)
            {
                PasteFromClipboard(true);
                e.Handled(true);
                return;
            }

            // Ctrl+A..Z -> control codes 0x01..0x1A
            if (ctrlDown && key >= VirtualKey::A && key <= VirtualKey::Z)
            {
                uint8_t code = static_cast<uint8_t>(static_cast<int>(key) - static_cast<int>(VirtualKey::A) + 1);
                OnCharInput(code);
                e.Handled(true);
                return;
            }
        }
        else
        {
            // Ctrl+C: copy selected text
            {
                auto ctrlState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Control);
                bool ctrlDown = (ctrlState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                                Windows::UI::Core::CoreVirtualKeyStates::Down;

                if (ctrlDown && key == VirtualKey::C)
                {
                    if (OutputBox().SelectionLength() > 0)
                    {
                        Windows::ApplicationModel::DataTransfer::DataPackage dp;
                        dp.SetText(TrimTrailingSpaces(OutputBox().SelectedText()));
                        Windows::ApplicationModel::DataTransfer::Clipboard::SetContent(dp);
                        OutputBox().Select(OutputBox().SelectionStart(), 0);
                    }
                    e.Handled(true);
                    return;
                }

                // Ctrl+V: paste clipboard text into input buffer + local echo
                if (ctrlDown && key == VirtualKey::V)
                {
                    PasteFromClipboard(false);
                    e.Handled(true);
                    return;
                }
            }

            // Generic mode: handle special keys for inline input
            switch (key)
            {
            case VirtualKey::Enter:
                SubmitGenericInput();
                e.Handled(true);
                return;
            case VirtualKey::Back:
                if (!m_inputLine.empty())
                {
                    m_inputLine.pop_back();
                    m_terminal.Write("\b \b");
                }
                e.Handled(true);
                return;
            // Suppress keys that would edit the TextBox
            case VirtualKey::Delete:
            case VirtualKey::Home:
            case VirtualKey::End:
            case VirtualKey::Left:
            case VirtualKey::Right:
            case VirtualKey::Up:
            case VirtualKey::Down:
            case VirtualKey::PageUp:
            case VirtualKey::PageDown:
            case VirtualKey::Insert:
            case VirtualKey::Tab:
            case VirtualKey::Escape:
                e.Handled(true);
                return;
            default:
                break;
            }
        }
    }

    void ConsoleWindow::OutputBox_CharacterReceived(
        [[maybe_unused]] UIElement const& sender,
        CharacterReceivedRoutedEventArgs const& e)
    {
        wchar_t wch = e.Character();
        if (wch == 0)
            return;

        // Convert wchar_t to single byte (ASCII range)
        char ch = static_cast<char>(wch & 0x7F);
        // Ignore control characters -- Enter/Tab/Backspace etc. are handled
        // by PreviewKeyDown, so skip CR/LF here to avoid double-sending.
        if (ch < 0x20)
            return;

        if (OnCharInput)
        {
            // MVME147 mode: send each character directly to SCC
            OnCharInput(static_cast<uint8_t>(ch));
        }
        else
        {
            // Generic mode: buffer and locally echo
            m_inputLine += ch;
            m_terminal.Write(ch);
        }

        e.Handled(true);
    }

    // ========================================================================
    // Input helpers
    // ========================================================================

    void ConsoleWindow::SubmitGenericInput()
    {
        std::string text = m_inputLine;
        m_inputLine.clear();

        {
            std::lock_guard lock(m_inputMutex);
            m_lineBuffer.push(text);
            for (char c : text)
                m_charBuffer.push(c);
            m_charBuffer.push('\n');
        }

        m_terminal.Write('\n');
    }

    void ConsoleWindow::OnContextCopy()
    {
        if (OutputBox().SelectionLength() > 0)
        {
            DataPackage dp;
            dp.SetText(TrimTrailingSpaces(OutputBox().SelectedText()));
            Clipboard::SetContent(dp);
        }
    }

    winrt::fire_and_forget ConsoleWindow::PasteFromClipboard(bool rawMode)
    {
        auto content = Clipboard::GetContent();
        if (!content.Contains(StandardDataFormats::Text()))
            co_return;

        auto htext = co_await content.GetTextAsync();
        std::string text = winrt::to_string(htext);

        // Normalize line endings: \r\n -> \r, \n -> \r
        std::string normalized;
        normalized.reserve(text.size());
        for (size_t i = 0; i < text.size(); ++i)
        {
            if (text[i] == '\r' && i + 1 < text.size() && text[i + 1] == '\n')
            {
                normalized += '\r';
                ++i; // skip \n
            }
            else if (text[i] == '\n')
            {
                normalized += '\r';
            }
            else
            {
                normalized += text[i];
            }
        }

        if (rawMode)
        {
            // MVME147 mode: send to SCC
            SendRawBytes(normalized);
        }
        else
        {
            // Generic mode: append to input buffer + local echo
            for (char c : normalized)
            {
                m_inputLine += c;
                m_terminal.Write(c);
            }
        }
    }

    void ConsoleWindow::SendRawBytes(const std::string& data)
    {
        if (!OnCharInput)
            return;
        for (char c : data)
            OnCharInput(static_cast<uint8_t>(c));
    }

    // ========================================================================
    // Search
    // ========================================================================

    void ConsoleWindow::OpenSearch()
    {
        m_searchMode = true;
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            if (auto bar = root.FindName(L"SearchBar").try_as<::winrt::Microsoft::UI::Xaml::UIElement>())
                bar.Visibility(Microsoft::UI::Xaml::Visibility::Visible);
            if (auto box = root.FindName(L"SearchBox").try_as<Controls::TextBox>())
            {
                // Pre-fill with selected text if any
                if (OutputBox() && OutputBox().SelectionLength() > 0)
                    box.Text(OutputBox().SelectedText());
                box.Focus(FocusState::Programmatic);
                box.SelectAll();
            }
        }
    }

    void ConsoleWindow::CloseSearch()
    {
        m_searchMode = false;
        m_searchIndex = -1;
        m_lastSearchText.clear();
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            if (auto bar = root.FindName(L"SearchBar").try_as<::winrt::Microsoft::UI::Xaml::UIElement>())
                bar.Visibility(Microsoft::UI::Xaml::Visibility::Collapsed);
            if (auto status = root.FindName(L"SearchStatus").try_as<Controls::TextBlock>())
                status.Text(L"");
        }
        // Return focus to OutputBox
        if (OutputBox())
            OutputBox().Focus(FocusState::Programmatic);
    }

    bool ConsoleWindow::IsRegexMode()
    {
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            if (auto toggle = root.FindName(L"RegexToggle").try_as<Controls::Primitives::ToggleButton>())
                return toggle.IsChecked().Value();
        }
        return false;
    }

    bool ConsoleWindow::IsCaseSensitive()
    {
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            if (auto toggle = root.FindName(L"CaseSensitiveToggle").try_as<Controls::Primitives::ToggleButton>())
                return toggle.IsChecked().Value();
        }
        return false;
    }

    // Collect all matches (pos, length) for the current search text
    std::vector<std::pair<int, int>> ConsoleWindow::CollectMatches(
        const std::string& text, const std::string& searchText,
        bool regexMode, bool caseSensitive)
    {
        std::vector<std::pair<int, int>> matches;
        if (searchText.empty() || text.empty()) return matches;

        if (regexMode)
        {
            try {
                auto flags = caseSensitive ? std::regex::ECMAScript : std::regex::icase;
                std::regex re(searchText, flags);
                auto begin = std::sregex_iterator(text.begin(), text.end(), re);
                auto end = std::sregex_iterator();
                for (auto it = begin; it != end; ++it)
                    matches.emplace_back(static_cast<int>(it->position()),
                                         static_cast<int>(it->length()));
            } catch (const std::regex_error&) {
                // Invalid regex — return empty
            }
        }
        else if (caseSensitive)
        {
            size_t pos = 0;
            while ((pos = text.find(searchText, pos)) != std::string::npos)
            {
                matches.emplace_back(static_cast<int>(pos), static_cast<int>(searchText.size()));
                pos += searchText.size();
            }
        }
        else
        {
            auto textLower = text;
            auto searchLower = searchText;
            for (auto& c : textLower) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
            for (auto& c : searchLower) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));

            size_t pos = 0;
            while ((pos = textLower.find(searchLower, pos)) != std::string::npos)
            {
                matches.emplace_back(static_cast<int>(pos), static_cast<int>(searchLower.size()));
                pos += searchLower.size();
            }
        }
        return matches;
    }

    void ConsoleWindow::FindNext()
    {
        if (!OutputBox()) return;
        auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>();
        if (!root) return;
        auto searchBox = root.FindName(L"SearchBox").try_as<Controls::TextBox>();
        if (!searchBox) return;

        auto searchText = winrt::to_string(searchBox.Text());
        if (searchText.empty()) return;

        auto text = winrt::to_string(OutputBox().Text());
        if (text.empty()) return;

        bool regexMode = IsRegexMode();
        bool caseSensitive = IsCaseSensitive();

        if (searchText != m_lastSearchText)
        {
            m_searchIndex = -1;
            m_lastSearchText = searchText;
        }

        auto matches = CollectMatches(text, searchText, regexMode, caseSensitive);
        if (matches.empty())
        {
            m_searchIndex = -1;
            if (auto status = root.FindName(L"SearchStatus").try_as<Controls::TextBlock>())
                status.Text(regexMode ? L"No match" : L"Not found");
            return;
        }

        // Find next match after current position
        int nextIdx = -1;
        for (int i = 0; i < static_cast<int>(matches.size()); i++)
        {
            if (matches[i].first > m_searchIndex) { nextIdx = i; break; }
        }
        if (nextIdx < 0) nextIdx = 0; // wrap around

        m_searchIndex = matches[nextIdx].first;
        HighlightMatch(matches[nextIdx].first, matches[nextIdx].second,
                        nextIdx + 1, static_cast<int>(matches.size()));
    }

    void ConsoleWindow::FindPrev()
    {
        if (!OutputBox()) return;
        auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>();
        if (!root) return;
        auto searchBox = root.FindName(L"SearchBox").try_as<Controls::TextBox>();
        if (!searchBox) return;

        auto searchText = winrt::to_string(searchBox.Text());
        if (searchText.empty()) return;

        auto text = winrt::to_string(OutputBox().Text());
        if (text.empty()) return;

        bool regexMode = IsRegexMode();
        bool caseSensitive = IsCaseSensitive();

        if (searchText != m_lastSearchText)
        {
            m_searchIndex = static_cast<int>(text.size());
            m_lastSearchText = searchText;
        }

        auto matches = CollectMatches(text, searchText, regexMode, caseSensitive);
        if (matches.empty())
        {
            m_searchIndex = -1;
            if (auto status = root.FindName(L"SearchStatus").try_as<Controls::TextBlock>())
                status.Text(regexMode ? L"No match" : L"Not found");
            return;
        }

        // Find previous match before current position
        int prevIdx = -1;
        for (int i = static_cast<int>(matches.size()) - 1; i >= 0; i--)
        {
            if (matches[i].first < m_searchIndex) { prevIdx = i; break; }
        }
        if (prevIdx < 0) prevIdx = static_cast<int>(matches.size()) - 1; // wrap

        m_searchIndex = matches[prevIdx].first;
        HighlightMatch(matches[prevIdx].first, matches[prevIdx].second,
                        prevIdx + 1, static_cast<int>(matches.size()));
    }

    void ConsoleWindow::HighlightMatch(int pos, int length, int current, int total)
    {
        if (!OutputBox()) return;

        OutputBox().Focus(FocusState::Programmatic);

        m_suppressScrollEvent = true;
        OutputBox().Select(pos, length);
        m_autoScroll = false;

        DispatcherQueue().TryEnqueue(
            Microsoft::UI::Dispatching::DispatcherQueuePriority::Low,
            [this]() { m_suppressScrollEvent = false; });

        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            if (auto status = root.FindName(L"SearchStatus").try_as<Controls::TextBlock>())
                status.Text(winrt::to_hstring(std::format("{}/{}", current, total)));
        }
    }
}
