#include "pch.h"
#include "Views/ConsoleWindow.xaml.h"
#if __has_include("ConsoleWindow.g.cpp")
#include "ConsoleWindow.g.cpp"
#endif

using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Input;
using namespace Microsoft::UI::Dispatching;
using namespace Microsoft::UI::Input;
using namespace Windows::System;
using namespace Windows::ApplicationModel::DataTransfer;

// ============================================================================
// XAML template implementations (normally generated by XAML compiler Pass2)
// ============================================================================
namespace winrt::Em68030::implementation
{
    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///Views/ConsoleWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator);
        }
    }

    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::Connect(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        _contentLoaded = true;
    }

    template <typename D, typename... I>
    ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector
    ConsoleWindowT<D, I...>::GetBindingConnector(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        return nullptr;
    }

    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const&)
    {
        throw ::winrt::hresult_not_implemented();
    }

    template <typename D, typename... I>
    void ConsoleWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
    }
}

namespace winrt::Em68030::implementation
{
    ConsoleWindow::ConsoleWindow()
        : m_terminal(80, 24, 2000)
    {
        InitializeComponent();

        // Populate named elements via FindName on the Window's content tree
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            OutputBox(root.FindName(L"OutputBox").try_as<Microsoft::UI::Xaml::Controls::TextBox>());
            ScrollbackButton(root.FindName(L"ScrollbackButton").try_as<Microsoft::UI::Xaml::Controls::Button>());
        }

        // Wire event handlers programmatically (XAML Connect is no-op for C++ native)
        if (OutputBox())
        {
            OutputBox().PreviewKeyDown({ this, &ConsoleWindow::OutputBox_KeyDown });
            OutputBox().CharacterReceived({ this, &ConsoleWindow::OutputBox_CharacterReceived });

            // Custom context menu: Copy, Paste, Select All
            // (IsReadOnly TextBox doesn't show Paste in the default menu)
            auto menuFlyout = Microsoft::UI::Xaml::Controls::MenuFlyout();

            auto copyItem = Microsoft::UI::Xaml::Controls::MenuFlyoutItem();
            copyItem.Text(L"Copy");
            copyItem.KeyboardAcceleratorTextOverride(L"Ctrl+C");
            copyItem.Click([this](auto&&, auto&&) { OnContextCopy(); });
            menuFlyout.Items().Append(copyItem);

            auto pasteItem = Microsoft::UI::Xaml::Controls::MenuFlyoutItem();
            pasteItem.Text(L"Paste");
            pasteItem.KeyboardAcceleratorTextOverride(L"Ctrl+V");
            pasteItem.Click([this](auto&&, auto&&) { PasteFromClipboard(OnCharInput != nullptr); });
            menuFlyout.Items().Append(pasteItem);

            auto selectAllItem = Microsoft::UI::Xaml::Controls::MenuFlyoutItem();
            selectAllItem.Text(L"Select All");
            selectAllItem.KeyboardAcceleratorTextOverride(L"Ctrl+A");
            selectAllItem.Click([this](auto&&, auto&&) { OutputBox().SelectAll(); });
            menuFlyout.Items().Append(selectAllItem);

            OutputBox().ContextFlyout(menuFlyout);
        }
        if (ScrollbackButton())
        {
            ScrollbackButton().Click({ this, &ConsoleWindow::ScrollbackToggle_Click });
        }

        Title(L"Console");
        AppWindow().Resize({ 700, 510 });

        // Create a DispatcherQueueTimer for 100ms render updates.
        // This is the WinUI 3 equivalent of WPF's DispatcherTimer.
        auto dispatcherQueue = DispatcherQueue();
        m_renderTimer = dispatcherQueue.CreateTimer();
        m_renderTimer.Interval(std::chrono::milliseconds(100));
        m_renderTimerToken = m_renderTimer.Tick([this](auto&&, auto&&)
        {
            RenderScreen();
        });
        m_renderTimer.Start();

        // Focus the output TextBox for keyboard capture
        // Use Loaded event for reliable initial focus (Activated can fire before content is ready)
        if (auto root = Content().try_as<::winrt::Microsoft::UI::Xaml::FrameworkElement>())
        {
            root.Loaded([this](auto&&, auto&&)
            {
                if (OutputBox())
                    OutputBox().Focus(FocusState::Programmatic);
            });
        }
        // Also re-focus on window re-activation
        Activated([this](auto&&, Microsoft::UI::Xaml::WindowActivatedEventArgs const& args)
        {
            if (args.WindowActivationState() != Microsoft::UI::Xaml::WindowActivationState::Deactivated)
            {
                if (OutputBox())
                    OutputBox().Focus(FocusState::Programmatic);
            }
        });

        // Stop render timer when window is closed (prevents accessing dead UI)
        Closed([this](auto&&, auto&&)
        {
            if (m_renderTimer)
            {
                m_renderTimer.Stop();
                m_renderTimer = nullptr;
            }
        });
    }

    // ========================================================================
    // Scrollback resize (called from UI thread)
    // ========================================================================

    void ConsoleWindow::SetScrollbackLines(int lines)
    {
        m_terminal.ResizeScrollback(lines);
    }

    // Thread-safe output (called from emulation thread)
    // ========================================================================

    void ConsoleWindow::AppendChar(char ch)
    {
        std::lock_guard lock(m_outputMutex);
        m_outputQueue.push(ch);
    }

    void ConsoleWindow::AppendString(const std::string& s)
    {
        std::lock_guard lock(m_outputMutex);
        for (char ch : s)
            m_outputQueue.push(ch);
    }

    // ========================================================================
    // Thread-safe input (called from emulation thread)
    // ========================================================================

    char ConsoleWindow::ReadChar()
    {
        std::lock_guard lock(m_inputMutex);
        if (!m_charBuffer.empty())
        {
            char ch = m_charBuffer.front();
            m_charBuffer.pop();
            return ch;
        }
        return '\0';
    }

    std::string ConsoleWindow::ReadString()
    {
        std::lock_guard lock(m_inputMutex);
        if (!m_lineBuffer.empty())
        {
            std::string line = m_lineBuffer.front();
            m_lineBuffer.pop();
            return line;
        }
        return "";
    }

    // ========================================================================
    // Render timer callback
    // ========================================================================

    void ConsoleWindow::RenderScreen()
    {
        // Drain output queue into the VT100 terminal emulator
        {
            std::lock_guard lock(m_outputMutex);
            while (!m_outputQueue.empty())
            {
                m_terminal.Write(m_outputQueue.front());
                m_outputQueue.pop();
            }
        }

        // Cursor blink: toggle every 5 ticks (500ms on, 500ms off at 100ms interval)
        m_blinkCounter++;
        bool newVisible = (m_blinkCounter / 5) % 2 == 0;
        bool blinkChanged = newVisible != m_cursorVisible;
        m_cursorVisible = newVisible;

        if (!m_terminal.IsDirty() && !blinkChanged)
            return;

        // Suspend text updates while the user has a text selection active,
        // so mouse-drag selections aren't reset every 100ms render tick.
        if (OutputBox().SelectionLength() > 0)
            return;

        m_terminal.ClearDirty();

        std::string rendered;
        if (m_showScrollback)
        {
            rendered = m_terminal.RenderFull();
        }
        else
        {
            rendered = m_cursorVisible
                ? m_terminal.RenderWithCursor()
                : m_terminal.Render();
        }

        OutputBox().Text(winrt::to_hstring(rendered));

        // Auto-scroll to bottom
        if (m_autoScroll)
        {
            // In WinUI 3, TextBox doesn't have ScrollToEnd().
            // We select the end of text to force scroll.
            auto textLength = OutputBox().Text().size();
            OutputBox().Select(static_cast<int32_t>(textLength), 0);
        }
    }

    // ========================================================================
    // Scrollback toggle
    // ========================================================================

    void ConsoleWindow::ScrollbackToggle_Click([[maybe_unused]] IInspectable const& sender,
                                               [[maybe_unused]] RoutedEventArgs const& e)
    {
        m_showScrollback = !m_showScrollback;
        ScrollbackButton().Content(winrt::box_value(m_showScrollback ? L"Live" : L"Log"));

        // Force re-render with the new mode
        m_terminal.SetDirty();
        RenderScreen();
    }

    // ========================================================================
    // Keyboard input handling
    // ========================================================================

    void ConsoleWindow::OutputBox_KeyDown([[maybe_unused]] IInspectable const& sender,
                                         KeyRoutedEventArgs const& e)
    {
        auto key = e.Key();

        if (OnCharInput)
        {
            // MVME147 mode: send VT100 sequences for special keys
            // Arrow keys use ESC O x in application mode (DECCKM), ESC [ x in normal mode
            std::string arrow = m_terminal.GetApplicationCursorKeys() ? "\x1BO" : "\x1B[";
            std::string seq;

            switch (key)
            {
            case VirtualKey::Enter:    seq = "\r"; break;
            case VirtualKey::Up:       seq = arrow + "A"; break;
            case VirtualKey::Down:     seq = arrow + "B"; break;
            case VirtualKey::Left:     seq = arrow + "D"; break;
            case VirtualKey::Right:    seq = arrow + "C"; break;
            case VirtualKey::Home:     seq = "\x1B[H"; break;
            case VirtualKey::End:      seq = "\x1B[F"; break;
            case VirtualKey::Back:     seq = "\b"; break;
            case VirtualKey::Delete:   seq = "\x1B[3~"; break;
            case VirtualKey::Tab:      seq = "\t"; break;
            case VirtualKey::Escape:   seq = "\x1B"; break;
            case VirtualKey::PageUp:   seq = "\x1B[5~"; break;
            case VirtualKey::PageDown: seq = "\x1B[6~"; break;
            case VirtualKey::Insert:   seq = "\x1B[2~"; break;
            case VirtualKey::F1:       seq = "\x1BOP"; break;
            case VirtualKey::F2:       seq = "\x1BOQ"; break;
            case VirtualKey::F3:       seq = "\x1BOR"; break;
            case VirtualKey::F4:       seq = "\x1BOS"; break;
            case VirtualKey::F5:       seq = "\x1B[15~"; break;
            case VirtualKey::F6:       seq = "\x1B[17~"; break;
            case VirtualKey::F7:       seq = "\x1B[18~"; break;
            case VirtualKey::F8:       seq = "\x1B[19~"; break;
            case VirtualKey::F9:       seq = "\x1B[20~"; break;
            case VirtualKey::F10:      seq = "\x1B[21~"; break;
            case VirtualKey::F11:      seq = "\x1B[23~"; break;
            case VirtualKey::F12:      seq = "\x1B[24~"; break;
            default: break;
            }

            if (!seq.empty())
            {
                SendRawBytes(seq);
                e.Handled(true);
                return;
            }

            // Ctrl key state (used for Ctrl+C, Ctrl+V, Ctrl+A..Z)
            auto ctrlState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Control);
            bool ctrlDown = (ctrlState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                            Windows::UI::Core::CoreVirtualKeyStates::Down;

            // Ctrl+C: copy selected text, or send 0x03 (ETX) if no selection
            if (ctrlDown && key == VirtualKey::C)
            {
                if (OutputBox().SelectionLength() > 0)
                {
                    Windows::ApplicationModel::DataTransfer::DataPackage dp;
                    dp.SetText(OutputBox().SelectedText());
                    Windows::ApplicationModel::DataTransfer::Clipboard::SetContent(dp);
                    OutputBox().Select(OutputBox().SelectionStart(), 0);
                }
                else
                {
                    OnCharInput(0x03);
                }
                e.Handled(true);
                return;
            }

            // Ctrl+V: paste clipboard text into SCC
            if (ctrlDown && key == VirtualKey::V)
            {
                PasteFromClipboard(true);
                e.Handled(true);
                return;
            }

            // Ctrl+A..Z -> control codes 0x01..0x1A
            if (ctrlDown && key >= VirtualKey::A && key <= VirtualKey::Z)
            {
                uint8_t code = static_cast<uint8_t>(static_cast<int>(key) - static_cast<int>(VirtualKey::A) + 1);
                OnCharInput(code);
                e.Handled(true);
                return;
            }
        }
        else
        {
            // Ctrl+C: copy selected text
            {
                auto ctrlState = InputKeyboardSource::GetKeyStateForCurrentThread(VirtualKey::Control);
                bool ctrlDown = (ctrlState & Windows::UI::Core::CoreVirtualKeyStates::Down) ==
                                Windows::UI::Core::CoreVirtualKeyStates::Down;

                if (ctrlDown && key == VirtualKey::C)
                {
                    if (OutputBox().SelectionLength() > 0)
                    {
                        Windows::ApplicationModel::DataTransfer::DataPackage dp;
                        dp.SetText(OutputBox().SelectedText());
                        Windows::ApplicationModel::DataTransfer::Clipboard::SetContent(dp);
                        OutputBox().Select(OutputBox().SelectionStart(), 0);
                    }
                    e.Handled(true);
                    return;
                }

                // Ctrl+V: paste clipboard text into input buffer + local echo
                if (ctrlDown && key == VirtualKey::V)
                {
                    PasteFromClipboard(false);
                    e.Handled(true);
                    return;
                }
            }

            // Generic mode: handle special keys for inline input
            switch (key)
            {
            case VirtualKey::Enter:
                SubmitGenericInput();
                e.Handled(true);
                return;
            case VirtualKey::Back:
                if (!m_inputLine.empty())
                {
                    m_inputLine.pop_back();
                    m_terminal.Write("\b \b");
                }
                e.Handled(true);
                return;
            // Suppress keys that would edit the TextBox
            case VirtualKey::Delete:
            case VirtualKey::Home:
            case VirtualKey::End:
            case VirtualKey::Left:
            case VirtualKey::Right:
            case VirtualKey::Up:
            case VirtualKey::Down:
            case VirtualKey::PageUp:
            case VirtualKey::PageDown:
            case VirtualKey::Insert:
            case VirtualKey::Tab:
            case VirtualKey::Escape:
                e.Handled(true);
                return;
            default:
                break;
            }
        }
    }

    void ConsoleWindow::OutputBox_CharacterReceived(
        [[maybe_unused]] UIElement const& sender,
        CharacterReceivedRoutedEventArgs const& e)
    {
        wchar_t wch = e.Character();
        if (wch == 0)
            return;

        // Convert wchar_t to single byte (ASCII range)
        char ch = static_cast<char>(wch & 0x7F);
        // Ignore control characters -- Enter/Tab/Backspace etc. are handled
        // by PreviewKeyDown, so skip CR/LF here to avoid double-sending.
        if (ch < 0x20)
            return;

        if (OnCharInput)
        {
            // MVME147 mode: send each character directly to SCC
            OnCharInput(static_cast<uint8_t>(ch));
        }
        else
        {
            // Generic mode: buffer and locally echo
            m_inputLine += ch;
            m_terminal.Write(ch);
        }

        e.Handled(true);
    }

    // ========================================================================
    // Input helpers
    // ========================================================================

    void ConsoleWindow::SubmitGenericInput()
    {
        std::string text = m_inputLine;
        m_inputLine.clear();

        {
            std::lock_guard lock(m_inputMutex);
            m_lineBuffer.push(text);
            for (char c : text)
                m_charBuffer.push(c);
            m_charBuffer.push('\n');
        }

        m_terminal.Write('\n');
    }

    void ConsoleWindow::OnContextCopy()
    {
        if (OutputBox().SelectionLength() > 0)
        {
            DataPackage dp;
            dp.SetText(OutputBox().SelectedText());
            Clipboard::SetContent(dp);
        }
    }

    winrt::fire_and_forget ConsoleWindow::PasteFromClipboard(bool rawMode)
    {
        auto content = Clipboard::GetContent();
        if (!content.Contains(StandardDataFormats::Text()))
            co_return;

        auto htext = co_await content.GetTextAsync();
        std::string text = winrt::to_string(htext);

        // Normalize line endings: \r\n -> \r, \n -> \r
        std::string normalized;
        normalized.reserve(text.size());
        for (size_t i = 0; i < text.size(); ++i)
        {
            if (text[i] == '\r' && i + 1 < text.size() && text[i + 1] == '\n')
            {
                normalized += '\r';
                ++i; // skip \n
            }
            else if (text[i] == '\n')
            {
                normalized += '\r';
            }
            else
            {
                normalized += text[i];
            }
        }

        if (rawMode)
        {
            // MVME147 mode: send to SCC
            SendRawBytes(normalized);
        }
        else
        {
            // Generic mode: append to input buffer + local echo
            for (char c : normalized)
            {
                m_inputLine += c;
                m_terminal.Write(c);
            }
        }
    }

    void ConsoleWindow::SendRawBytes(const std::string& data)
    {
        if (!OnCharInput)
            return;
        for (char c : data)
            OnCharInput(static_cast<uint8_t>(c));
    }
}
