// Copyright 2026 hha0x617
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "pch.h"
#include "Views/InputDialog.xaml.h"
#if __has_include("InputDialog.g.cpp")
#include "InputDialog.g.cpp"
#endif

using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Controls;
using namespace Windows::Foundation;

// ============================================================================
// XAML template implementations (normally generated by XAML compiler Pass2;
// provided manually because the WinUI 3 NuGet does not wire Pass2 into the
// C++ native build chain)
// ============================================================================
namespace winrt::Em68030::implementation
{
    template <typename D, typename... I>
    void InputDialogT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///Views/InputDialog.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator);
        }
    }

    template <typename D, typename... I>
    void InputDialogT<D, I...>::Connect(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        _contentLoaded = true;
    }

    template <typename D, typename... I>
    ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector
    InputDialogT<D, I...>::GetBindingConnector(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        return nullptr;
    }

    template <typename D, typename... I>
    void InputDialogT<D, I...>::UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const&)
    {
        throw ::winrt::hresult_not_implemented();
    }

    template <typename D, typename... I>
    void InputDialogT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
    }
}

namespace winrt::Em68030::implementation
{
    InputDialog::InputDialog()
    {
        InitializeComponent();

        // Populate named elements via FindName (ContentDialog is a FrameworkElement)
        PromptText(FindName(L"PromptText").try_as<Controls::TextBlock>());
        InputTextBox(FindName(L"InputTextBox").try_as<Controls::TextBox>());
    }

    IAsyncOperation<winrt::hstring> InputDialog::ShowAsync(
        winrt::hstring title,
        winrt::hstring prompt,
        winrt::hstring defaultValue,
        UIElement const& parent)
    {
        // Configure the dialog
        this->Title(winrt::box_value(title));
        PromptText().Text(prompt);
        InputTextBox().Text(defaultValue);
        InputTextBox().SelectAll();

        // Set XamlRoot from the parent element (required for WinUI 3 ContentDialog)
        this->XamlRoot(parent.XamlRoot());

        // Show the dialog (call base ContentDialog::ShowAsync via projected type)
        auto dialog = this->try_as<ContentDialog>();
        auto result = co_await dialog.ShowAsync();

        if (result == ContentDialogResult::Primary)
        {
            co_return InputTextBox().Text();
        }

        co_return winrt::hstring{};
    }

    winrt::hstring InputDialog::InputText()
    {
        return InputTextBox().Text();
    }
}
