#include "pch.h"
#include "Views/SettingsWindow.xaml.h"
#if __has_include("SettingsWindow.g.cpp")
#include "SettingsWindow.g.cpp"
#endif

#include <microsoft.ui.xaml.window.h>
#include <shobjidl_core.h>
#include <winrt/Windows.Storage.Pickers.h>
#include <set>
#include <winrt/Microsoft.UI.Xaml.Media.h>

#include "IO/HddDevice.h"
#include "IO/SlirpNetworkHandler.h"

using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Controls;
using namespace Windows::Foundation;
using namespace Windows::Storage::Pickers;

// ============================================================================
// XAML template implementations (normally generated by XAML compiler Pass2)
// ============================================================================
namespace winrt::Em68030::implementation
{
    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///Views/SettingsWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator);
        }
    }

    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::Connect(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        _contentLoaded = true;
    }

    template <typename D, typename... I>
    ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector
    SettingsWindowT<D, I...>::GetBindingConnector(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        return nullptr;
    }

    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const&)
    {
        throw ::winrt::hresult_not_implemented();
    }

    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
    }
}

namespace winrt::Em68030::implementation
{
    SettingsWindow::SettingsWindow()
    {
        InitializeComponent();

        // Populate named elements via FindName (ContentDialog is a FrameworkElement)
        BoardTypeBox(FindName(L"BoardTypeBox").try_as<Controls::ComboBox>());
        Mvme147Panel(FindName(L"Mvme147Panel").try_as<Controls::StackPanel>());
        // Mvme147RamBox removed — MemSizeBox is shared for all board types
        Mvme147RomBox(FindName(L"Mvme147RomBox").try_as<Controls::TextBox>());
        ScsiDiskListPanel(FindName(L"ScsiDiskListPanel").try_as<Controls::StackPanel>());
        NewScsiImageSizeBox(FindName(L"NewScsiImageSizeBox").try_as<Controls::TextBox>());
        ScsiCdromPathBox(FindName(L"ScsiCdromPathBox").try_as<Controls::TextBox>());
        ScsiCdromIdBox(FindName(L"ScsiCdromIdBox").try_as<Controls::ComboBox>());
        MemSizeBox(FindName(L"MemSizeBox").try_as<Controls::TextBox>());
        ConsoleEnabledBox(FindName(L"ConsoleEnabledBox").try_as<Controls::CheckBox>());
        ConsoleAddrBox(FindName(L"ConsoleAddrBox").try_as<Controls::TextBox>());
        ConsoleScrollbackBox(FindName(L"ConsoleScrollbackBox").try_as<Controls::TextBox>());
        ConsoleColumnsBox(FindName(L"ConsoleColumnsBox").try_as<Controls::TextBox>());
        ConsoleRowsBox(FindName(L"ConsoleRowsBox").try_as<Controls::TextBox>());
        HddEnabledBox(FindName(L"HddEnabledBox").try_as<Controls::CheckBox>());
        HddAddrBox(FindName(L"HddAddrBox").try_as<Controls::TextBox>());
        HddPathBox(FindName(L"HddPathBox").try_as<Controls::TextBox>());
        NewImageSizeBox(FindName(L"NewImageSizeBox").try_as<Controls::TextBox>());
        FontFamilyBox(FindName(L"FontFamilyBox").try_as<Controls::TextBox>());
        FontSizeBox(FindName(L"FontSizeBox").try_as<Controls::TextBox>());
        JitEnabledBox(FindName(L"JitEnabledBox").try_as<Controls::CheckBox>());
        JitMinBlockLengthBox(FindName(L"JitMinBlockLengthBox").try_as<Controls::TextBox>());
        JitCompileThresholdBox(FindName(L"JitCompileThresholdBox").try_as<Controls::TextBox>());
        AddScsiDiskBtn(FindName(L"AddScsiDiskBtn").try_as<Controls::Button>());
        NetworkModeBox(FindName(L"NetworkModeBox").try_as<Controls::ComboBox>());
        NatGatewayIpBox(FindName(L"NatGatewayIpBox").try_as<Controls::TextBox>());
        NatGatewayMacBox(FindName(L"NatGatewayMacBox").try_as<Controls::TextBox>());

        // Wire event handlers programmatically (XAML Connect is no-op for C++ native)
        if (BoardTypeBox())
        {
            BoardTypeBox().SelectionChanged({ this, &SettingsWindow::BoardType_Changed });
        }
        if (auto btn = FindName(L"BrowseRomBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::BrowseRom_Click });
        if (auto btn = FindName(L"CreateScsiImageBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::CreateScsiImage_Click });
        if (auto btn = FindName(L"BrowseScsiCdromBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::BrowseScsiCdrom_Click });
        if (auto btn = FindName(L"BrowseHddBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::BrowseHdd_Click });
        if (auto btn = FindName(L"CreateHddImageBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::CreateImage_Click });
        if (AddScsiDiskBtn())
        {
            AddScsiDiskBtn().Click([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                // Find first free SCSI ID
                std::set<int> usedIds;
                for (auto& row : m_diskRows)
                    usedIds.insert(GetSelectedScsiId(row.IdBox));
                usedIds.insert(GetSelectedScsiId(ScsiCdromIdBox()));
                int freeId = 0;
                for (int i = 0; i <= 6; i++) {
                    if (usedIds.find(i) == usedIds.end()) { freeId = i; break; }
                }
                AddDiskRow("", freeId);
                RefreshScsiIdOptions();
            });
        }
        if (ScsiCdromIdBox())
        {
            ScsiCdromIdBox().SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                if (!m_refreshingIds) RefreshScsiIdOptions();
            });
        }
        if (NetworkModeBox())
        {
            NetworkModeBox().SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                UpdateNatGatewayEnabled();
            });
        }
    }

    // ========================================================================
    // Dynamic SCSI disk row management
    // ========================================================================

    void SettingsWindow::AddDiskRow(const std::string& path, int scsiId)
    {
        DiskRowState row;
        row.DesiredId = scsiId;

        // ID label
        TextBlock idLabel;
        idLabel.Text(L"ID:");
        idLabel.FontSize(13);
        idLabel.VerticalAlignment(VerticalAlignment::Center);
        idLabel.Margin(ThicknessHelper::FromLengths(0, 0, 4, 0));

        // ID ComboBox - items populated by RefreshScsiIdOptions
        ComboBox idBox;
        idBox.Width(70);
        idBox.VerticalAlignment(VerticalAlignment::Center);
        idBox.Margin(ThicknessHelper::FromLengths(0, 0, 4, 0));
        idBox.SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            if (!m_refreshingIds) RefreshScsiIdOptions();
        });
        row.IdBox = idBox;

        // Path TextBox
        TextBox pathBox;
        pathBox.Text(winrt::to_hstring(path));
        pathBox.MinWidth(160);
        pathBox.FontFamily(Media::FontFamily(L"Consolas"));
        pathBox.VerticalAlignment(VerticalAlignment::Center);
        row.PathBox = pathBox;

        // Browse button
        Button browseBtn;
        browseBtn.Content(box_value(L"..."));
        browseBtn.Width(30);
        browseBtn.Margin(ThicknessHelper::FromLengths(4, 0, 0, 0));
        browseBtn.VerticalAlignment(VerticalAlignment::Center);
        size_t rowIndex = m_diskRows.size(); // capture current index
        browseBtn.Click([this, pathBox]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            BrowseFile(L"Disk Image", L".img", L"Select SCSI Disk Image", pathBox);
        });
        row.BrowseBtn = browseBtn;

        // Remove button
        Button removeBtn;
        removeBtn.Content(box_value(L"\u00D7"));
        removeBtn.Width(36);
        removeBtn.Margin(ThicknessHelper::FromLengths(4, 0, 0, 0));
        removeBtn.VerticalAlignment(VerticalAlignment::Center);
        row.RemoveBtn = removeBtn;

        // Row grid (ensures TextBox fills remaining space, buttons always visible)
        Grid grid;
        grid.Margin(ThicknessHelper::FromLengths(0, 2, 0, 2));
        auto colAuto = Controls::ColumnDefinition();
        colAuto.Width(GridLengthHelper::Auto());
        auto colAuto2 = Controls::ColumnDefinition();
        colAuto2.Width(GridLengthHelper::Auto());
        auto colStar = Controls::ColumnDefinition();
        colStar.Width(GridLengthHelper::FromValueAndType(1, GridUnitType::Star));
        auto colAuto3 = Controls::ColumnDefinition();
        colAuto3.Width(GridLengthHelper::Auto());
        auto colAuto4 = Controls::ColumnDefinition();
        colAuto4.Width(GridLengthHelper::Auto());
        grid.ColumnDefinitions().Append(colAuto);
        grid.ColumnDefinitions().Append(colAuto2);
        grid.ColumnDefinitions().Append(colStar);
        grid.ColumnDefinitions().Append(colAuto3);
        grid.ColumnDefinitions().Append(colAuto4);
        Grid::SetColumn(idLabel, 0);
        Grid::SetColumn(idBox, 1);
        Grid::SetColumn(pathBox, 2);
        Grid::SetColumn(browseBtn, 3);
        Grid::SetColumn(removeBtn, 4);
        grid.Children().Append(idLabel);
        grid.Children().Append(idBox);
        grid.Children().Append(pathBox);
        grid.Children().Append(browseBtn);
        grid.Children().Append(removeBtn);
        row.RowPanel = grid;

        m_diskRows.push_back(row);

        // Wire remove button with captured index that finds row by grid identity
        removeBtn.Click([this, grid]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            for (size_t i = 0; i < m_diskRows.size(); i++) {
                if (m_diskRows[i].RowPanel == grid) {
                    RemoveDiskRow(i);
                    break;
                }
            }
        });

        ScsiDiskListPanel().Children().Append(grid);
    }

    void SettingsWindow::RemoveDiskRow(size_t index)
    {
        if (index >= m_diskRows.size()) return;
        auto panel = m_diskRows[index].RowPanel;
        uint32_t idx = 0;
        if (ScsiDiskListPanel().Children().IndexOf(panel, idx))
            ScsiDiskListPanel().Children().RemoveAt(idx);
        m_diskRows.erase(m_diskRows.begin() + static_cast<ptrdiff_t>(index));
        RefreshScsiIdOptions();
    }

    int SettingsWindow::GetSelectedScsiId(const ComboBox& box) const
    {
        if (box && box.SelectedItem())
        {
            if (auto item = box.SelectedItem().try_as<ComboBoxItem>())
            {
                auto content = item.Content();
                if (content)
                {
                    try { return std::stoi(winrt::to_string(winrt::unbox_value<winrt::hstring>(content))); }
                    catch (...) {}
                }
            }
        }
        return 0;
    }

    void SettingsWindow::RefreshScsiIdOptions()
    {
        if (m_refreshingIds) return;
        m_refreshingIds = true;

        // Collect current IDs for each disk row
        std::vector<int> diskIds(m_diskRows.size());
        for (size_t i = 0; i < m_diskRows.size(); i++)
        {
            auto& row = m_diskRows[i];
            if (row.IdBox && row.IdBox.SelectedItem())
                diskIds[i] = GetSelectedScsiId(row.IdBox);
            else
                diskIds[i] = row.DesiredId;
        }

        int cdromId = (ScsiCdromIdBox() && ScsiCdromIdBox().SelectedItem())
                      ? GetSelectedScsiId(ScsiCdromIdBox())
                      : m_desiredCdromId;

        // Update each disk row's ComboBox
        for (size_t i = 0; i < m_diskRows.size(); i++)
        {
            auto& row = m_diskRows[i];
            int currentId = diskIds[i];

            std::set<int> otherIds;
            for (size_t j = 0; j < m_diskRows.size(); j++) {
                if (j != i) otherIds.insert(diskIds[j]);
            }
            otherIds.insert(cdromId);

            row.IdBox.Items().Clear();
            int selectIndex = 0;
            for (int id = 0; id <= 6; id++)
            {
                if (id != currentId && otherIds.find(id) != otherIds.end())
                    continue;
                ComboBoxItem item;
                item.Content(box_value(winrt::to_hstring(std::to_string(id))));
                row.IdBox.Items().Append(item);
                if (id == currentId)
                    selectIndex = static_cast<int>(row.IdBox.Items().Size()) - 1;
            }
            row.IdBox.SelectedIndex(selectIndex);
            row.DesiredId = currentId;
        }

        // Update CD-ROM ComboBox: exclude disk IDs
        if (ScsiCdromIdBox())
        {
            std::set<int> allDiskIds(diskIds.begin(), diskIds.end());
            int currentCdromId = cdromId;

            ScsiCdromIdBox().Items().Clear();
            int cdromSelectIndex = 0;
            for (int id = 0; id <= 6; id++)
            {
                if (id != currentCdromId && allDiskIds.find(id) != allDiskIds.end())
                    continue;
                ComboBoxItem item;
                item.Content(box_value(winrt::to_hstring(std::to_string(id))));
                ScsiCdromIdBox().Items().Append(item);
                if (id == currentCdromId)
                    cdromSelectIndex = static_cast<int>(ScsiCdromIdBox().Items().Size()) - 1;
            }
            ScsiCdromIdBox().SelectedIndex(cdromSelectIndex);
            m_desiredCdromId = currentCdromId;
        }

        // Update Add button: disable if all IDs taken
        if (AddScsiDiskBtn())
        {
            std::set<int> allUsed(diskIds.begin(), diskIds.end());
            allUsed.insert(cdromId);
            AddScsiDiskBtn().IsEnabled(allUsed.size() < 7);
        }

        m_refreshingIds = false;
    }

    // ========================================================================
    // LoadConfig / SaveConfig
    // ========================================================================

    void SettingsWindow::LoadConfig(const ::Em68030::Config::EmulatorConfig& config)
    {
        // Board type
        BoardTypeBox().SelectedIndex(config.BoardType == "MVME147" ? 1 : 0);
        Mvme147RomBox().Text(winrt::to_hstring(config.Mvme147RomPath));

        // SCSI Disks
        m_diskRows.clear();
        if (ScsiDiskListPanel())
            ScsiDiskListPanel().Children().Clear();
        for (const auto& disk : config.Mvme147ScsiDisks)
            AddDiskRow(disk.Path, disk.ScsiId);
        if (m_diskRows.empty())
            AddDiskRow("", 0);

        ScsiCdromPathBox().Text(winrt::to_hstring(config.Mvme147ScsiCdromPath));
        m_desiredCdromId = std::clamp(config.Mvme147ScsiCdromId, 0, 6);
        if (NetworkModeBox())
            NetworkModeBox().SelectedIndex(config.NetworkMode == "NAT" ? 1 : 0);
        if (NatGatewayIpBox())
            NatGatewayIpBox().Text(winrt::to_hstring(config.NatGatewayIp));
        if (NatGatewayMacBox())
            NatGatewayMacBox().Text(winrt::to_hstring(config.NatGatewayMac));
        UpdateNatGatewayEnabled();
        UpdateMvme147Visibility();
        RefreshScsiIdOptions();

        // Memory
        MemSizeBox().Text(winrt::to_hstring(std::to_string(config.MemorySize / (1024 * 1024))));

        // I/O
        ConsoleEnabledBox().IsChecked(config.ConsoleEnabled);
        {
            wchar_t buf[16];
            swprintf_s(buf, L"%08X", config.ConsoleBaseAddress);
            ConsoleAddrBox().Text(buf);
        }
        ConsoleScrollbackBox().Text(winrt::to_hstring(std::to_string(config.ConsoleScrollbackLines)));
        if (ConsoleColumnsBox())
            ConsoleColumnsBox().Text(winrt::to_hstring(std::to_string(config.ConsoleColumns)));
        if (ConsoleRowsBox())
            ConsoleRowsBox().Text(winrt::to_hstring(std::to_string(config.ConsoleRows)));
        HddEnabledBox().IsChecked(config.HddEnabled);
        {
            wchar_t buf[16];
            swprintf_s(buf, L"%08X", config.HddBaseAddress);
            HddAddrBox().Text(buf);
        }
        HddPathBox().Text(winrt::to_hstring(config.HddImagePath));

        // Performance
        if (JitEnabledBox())
            JitEnabledBox().IsChecked(config.JitEnabled);
        if (JitMinBlockLengthBox())
            JitMinBlockLengthBox().Text(winrt::to_hstring(std::to_string(config.JitMinBlockLength)));
        if (JitCompileThresholdBox())
            JitCompileThresholdBox().Text(winrt::to_hstring(std::to_string(config.JitCompileThreshold)));

        // Display
        FontFamilyBox().Text(winrt::to_hstring(config.FontFamily));
        FontSizeBox().Text(winrt::to_hstring(std::to_string(config.FontSize)));
    }

    bool SettingsWindow::SaveConfig(::Em68030::Config::EmulatorConfig& config)
    {
        // Board type
        config.BoardType = (BoardTypeBox().SelectedIndex() == 1) ? "MVME147" : "Generic";

        config.Mvme147RomPath = winrt::to_string(Mvme147RomBox().Text());

        // SCSI Disks
        config.Mvme147ScsiDisks.clear();
        for (auto& row : m_diskRows)
        {
            std::string path = winrt::to_string(row.PathBox.Text());
            int id = GetSelectedScsiId(row.IdBox);
            if (!path.empty())
                config.Mvme147ScsiDisks.push_back({ path, id });
        }

        config.Mvme147ScsiCdromPath = winrt::to_string(ScsiCdromPathBox().Text());
        config.Mvme147ScsiCdromId = GetSelectedScsiId(ScsiCdromIdBox());
        if (NetworkModeBox())
            config.NetworkMode = (NetworkModeBox().SelectedIndex() == 1) ? "NAT" : "Virtual";
        if (NatGatewayIpBox())
        {
            auto ip = winrt::to_string(NatGatewayIpBox().Text());
            // Validate: ParseIpAddress returns default on invalid input
            auto parsed = ::Em68030::IO::SlirpNetworkHandler::ParseIpAddress(ip);
            config.NatGatewayIp = std::to_string(parsed[0]) + "." + std::to_string(parsed[1]) + "." +
                                  std::to_string(parsed[2]) + "." + std::to_string(parsed[3]);
        }
        if (NatGatewayMacBox())
        {
            auto mac = winrt::to_string(NatGatewayMacBox().Text());
            auto parsed = ::Em68030::IO::SlirpNetworkHandler::ParseMacAddress(mac);
            char buf[18];
            snprintf(buf, sizeof(buf), "%02x:%02x:%02x:%02x:%02x:%02x",
                     parsed[0], parsed[1], parsed[2], parsed[3], parsed[4], parsed[5]);
            config.NatGatewayMac = buf;
        }

        // Memory size
        auto memText = winrt::to_string(MemSizeBox().Text());
        try { config.MemorySize = std::stoi(memText) * 1024 * 1024; }
        catch (...) { /* keep previous */ }

        // I/O
        config.ConsoleEnabled = ConsoleEnabledBox().IsChecked().Value();
        auto conAddrText = winrt::to_string(ConsoleAddrBox().Text());
        try { config.ConsoleBaseAddress = static_cast<uint32_t>(std::stoul(conAddrText, nullptr, 16)); }
        catch (...) { /* keep previous */ }

        auto scrollbackText = winrt::to_string(ConsoleScrollbackBox().Text());
        try { config.ConsoleScrollbackLines = std::stoi(scrollbackText); }
        catch (...) { /* keep previous */ }

        if (ConsoleColumnsBox())
        {
            try { config.ConsoleColumns = std::max(80, std::stoi(winrt::to_string(ConsoleColumnsBox().Text()))); }
            catch (...) { /* keep previous */ }
        }
        if (ConsoleRowsBox())
        {
            try { config.ConsoleRows = std::max(24, std::stoi(winrt::to_string(ConsoleRowsBox().Text()))); }
            catch (...) { /* keep previous */ }
        }

        config.HddEnabled = HddEnabledBox().IsChecked().Value();
        auto hddAddrText = winrt::to_string(HddAddrBox().Text());
        try { config.HddBaseAddress = static_cast<uint32_t>(std::stoul(hddAddrText, nullptr, 16)); }
        catch (...) { /* keep previous */ }

        config.HddImagePath = winrt::to_string(HddPathBox().Text());

        // Performance
        if (JitEnabledBox())
            config.JitEnabled = JitEnabledBox().IsChecked().Value();
        if (JitMinBlockLengthBox())
        {
            try { config.JitMinBlockLength = std::clamp(std::stoi(winrt::to_string(JitMinBlockLengthBox().Text())), 1, 64); }
            catch (...) { /* keep previous */ }
        }
        if (JitCompileThresholdBox())
        {
            try { config.JitCompileThreshold = std::clamp(std::stoi(winrt::to_string(JitCompileThresholdBox().Text())), 1, 255); }
            catch (...) { /* keep previous */ }
        }

        config.FontFamily = winrt::to_string(FontFamilyBox().Text());

        auto fontSizeText = winrt::to_string(FontSizeBox().Text());
        try { config.FontSize = std::stod(fontSizeText); }
        catch (...) { /* keep previous */ }

        return true;
    }

    // Recursively walk the visual tree to find a named element
    static DependencyObject FindChildByName(DependencyObject const& parent, hstring const& name)
    {
        int count = Media::VisualTreeHelper::GetChildrenCount(parent);
        for (int i = 0; i < count; i++)
        {
            auto child = Media::VisualTreeHelper::GetChild(parent, i);
            if (auto fe = child.try_as<FrameworkElement>())
            {
                if (fe.Name() == name)
                    return child;
            }
            auto result = FindChildByName(child, name);
            if (result != nullptr)
                return result;
        }
        return nullptr;
    }

    IAsyncOperation<ContentDialogResult> SettingsWindow::ShowAsync(UIElement const& parent)
    {
        this->XamlRoot(parent.XamlRoot());
        auto dialog = this->try_as<ContentDialog>();

        // Override the dialog's internal MaxWidth via the BackgroundElement in the template
        constexpr double dialogWidth = 640.0;
        auto openedToken = dialog.Opened([dialogWidth](ContentDialog const& sender, ContentDialogOpenedEventArgs const&) {
            auto bgElement = FindChildByName(sender, L"BackgroundElement");
            if (auto border = bgElement.try_as<Controls::Border>())
            {
                border.MaxWidth(dialogWidth);
                border.MinWidth(dialogWidth);
            }
            auto layoutRoot = FindChildByName(sender, L"LayoutRoot");
            if (auto grid = layoutRoot.try_as<Controls::Grid>())
            {
                grid.MaxWidth(dialogWidth);
            }
            // Disable the ContentDialog's internal ScrollViewer so that our
            // explicit ScrollViewer receives mouse wheel events directly.
            auto csvElement = FindChildByName(sender, L"ContentScrollViewer");
            if (auto csv = csvElement.try_as<Controls::ScrollViewer>())
            {
                csv.VerticalScrollMode(Controls::ScrollMode::Disabled);
                csv.VerticalScrollBarVisibility(Controls::ScrollBarVisibility::Disabled);
            }
        });

        auto result = co_await dialog.ShowAsync();
        dialog.Opened(openedToken);
        co_return result;
    }

    // ========================================================================
    // MVME147 panel visibility
    // ========================================================================

    void SettingsWindow::UpdateMvme147Visibility()
    {
        bool isMvme = BoardTypeBox().SelectedIndex() == 1;
        Mvme147Panel().Visibility(isMvme ? Visibility::Visible : Visibility::Collapsed);
    }

    void SettingsWindow::UpdateNatGatewayEnabled()
    {
        bool isNat = NetworkModeBox() && NetworkModeBox().SelectedIndex() == 1;
        if (NatGatewayIpBox())
        {
            NatGatewayIpBox().IsEnabled(isNat);
            NatGatewayIpBox().Opacity(isNat ? 1.0 : 0.35);
        }
        if (NatGatewayMacBox())
        {
            NatGatewayMacBox().IsEnabled(isNat);
            NatGatewayMacBox().Opacity(isNat ? 1.0 : 0.35);
        }
    }

    void SettingsWindow::BoardType_Changed([[maybe_unused]] IInspectable const& sender,
                                           [[maybe_unused]] SelectionChangedEventArgs const& e)
    {
        // Guard against calls during initialization before XAML elements exist
        if (Mvme147Panel())
        {
            UpdateMvme147Visibility();
        }
    }

    // ========================================================================
    // File browser helpers
    // ========================================================================

    HWND SettingsWindow::GetOwnerHwnd() const
    {
        // ContentDialog does not have its own HWND. We need to find the
        // parent Window's HWND via the XamlRoot. In practice, the caller
        // must set XamlRoot before calling ShowAsync, and we walk to find
        // the Window.
        // For file pickers in ContentDialog context, we use the foreground window.
        return ::GetActiveWindow();
    }

    winrt::fire_and_forget SettingsWindow::BrowseFile(winrt::hstring filterName, winrt::hstring filterExt,
                                                       winrt::hstring title,
                                                       TextBox targetBox)
    {
        FileOpenPicker picker;
        picker.as<::IInitializeWithWindow>()->Initialize(GetOwnerHwnd());
        picker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
        picker.FileTypeFilter().Append(filterExt);
        picker.FileTypeFilter().Append(L"*");

        auto file = co_await picker.PickSingleFileAsync();
        if (file != nullptr)
        {
            targetBox.Text(file.Path());
        }
    }

    winrt::fire_and_forget SettingsWindow::SaveFile(winrt::hstring filterName, winrt::hstring filterExt,
                                                     winrt::hstring title,
                                                     TextBox targetBox,
                                                     bool isScsiDisk)
    {
        FileSavePicker picker;
        picker.as<::IInitializeWithWindow>()->Initialize(GetOwnerHwnd());
        picker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
        picker.FileTypeChoices().Insert(filterName, single_threaded_vector<hstring>({ filterExt }));
        picker.SuggestedFileName(L"disk.img");

        auto file = co_await picker.PickSaveFileAsync();
        if (file == nullptr) co_return;

        auto filePath = winrt::to_string(file.Path());

        int sizeMB = 0;
        try
        {
            if (isScsiDisk)
                sizeMB = std::stoi(winrt::to_string(NewScsiImageSizeBox().Text()));
            else
                sizeMB = std::stoi(winrt::to_string(NewImageSizeBox().Text()));
        }
        catch (...) { co_return; }

        if (sizeMB <= 0) co_return;

        long long sizeBytes = static_cast<long long>(sizeMB) * 1024 * 1024;

        // Create the image file
        if (isScsiDisk)
        {
            // Create empty file and write NetBSD disklabel
            {
                std::ofstream ofs(filePath, std::ios::binary);
                if (ofs)
                {
                    ofs.seekp(sizeBytes - 1);
                    ofs.put('\0');
                }
            }
            // TODO: ScsiDisk::WriteNetBsdDisklabel(filePath);
        }
        else
        {
            ::Em68030::IO::HddDevice::CreateImage(filePath, sizeBytes);
        }

        targetBox.Text(file.Path());
    }

    // ========================================================================
    // Browse button handlers
    // ========================================================================

    void SettingsWindow::BrowseRom_Click([[maybe_unused]] IInspectable const& sender,
                                         [[maybe_unused]] RoutedEventArgs const& e)
    {
        BrowseFile(L"ROM Image", L".bin", L"Select MVME147 ROM Image", Mvme147RomBox());
    }

    void SettingsWindow::BrowseHdd_Click([[maybe_unused]] IInspectable const& sender,
                                         [[maybe_unused]] RoutedEventArgs const& e)
    {
        BrowseFile(L"HDD Image", L".img", L"Select HDD Image File", HddPathBox());
    }

    void SettingsWindow::BrowseScsiCdrom_Click([[maybe_unused]] IInspectable const& sender,
                                               [[maybe_unused]] RoutedEventArgs const& e)
    {
        BrowseFile(L"ISO Image", L".iso", L"Select SCSI CD-ROM ISO Image", ScsiCdromPathBox());
    }

    // ========================================================================
    // Create image handlers
    // ========================================================================

    void SettingsWindow::CreateScsiImage_Click([[maybe_unused]] IInspectable const& sender,
                                               [[maybe_unused]] RoutedEventArgs const& e)
    {
        // Find or create a target TextBox - use the first empty disk row, or create a new one
        TextBox targetBox{ nullptr };
        for (auto& row : m_diskRows) {
            if (row.PathBox && row.PathBox.Text().empty()) {
                targetBox = row.PathBox;
                break;
            }
        }
        if (!targetBox) {
            AddDiskRow("", 0);
            RefreshScsiIdOptions();
            targetBox = m_diskRows.back().PathBox;
        }
        SaveFile(L"Disk Image", L".img", L"Create SCSI Disk Image", targetBox, true);
    }

    void SettingsWindow::CreateImage_Click([[maybe_unused]] IInspectable const& sender,
                                           [[maybe_unused]] RoutedEventArgs const& e)
    {
        SaveFile(L"HDD Image", L".img", L"Create HDD Image File", HddPathBox(), false);
    }
}
