// Copyright 2026 hha0x617
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "pch.h"
#include "Views/SettingsWindow.xaml.h"
#if __has_include("SettingsWindow.g.cpp")
#include "SettingsWindow.g.cpp"
#endif

#include <microsoft.ui.xaml.window.h>
#include <shobjidl_core.h>
#include <winrt/Windows.Storage.Pickers.h>
#include <set>
#include <filesystem>
#include <winrt/Microsoft.UI.Xaml.Media.h>

#include "Helpers/ResourceHelper.h"
#include "IO/HddDevice.h"
#include "IO/ScsiDisk.h"
#include "IO/SlirpNetworkHandler.h"

using ::Em68030::ResourceHelper;
using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Controls;
using namespace Windows::Foundation;
using namespace Windows::Storage::Pickers;

// Helper: get the Content string of the currently selected ComboBoxItem.
static std::string GetSelectedItemText(const Controls::ComboBox& box)
{
    if (!box) return {};
    auto item = box.SelectedItem();
    if (!item) return {};
    if (auto cbi = item.try_as<Controls::ComboBoxItem>())
        return winrt::to_string(cbi.Content().as<winrt::hstring>());
    return {};
}

// Helper: select a ComboBoxItem whose Content matches the given text.
// Falls back to index 0 if no match is found.
static void SelectItemByText(const Controls::ComboBox& box, const std::string& text)
{
    if (!box) return;
    for (int i = 0; i < static_cast<int>(box.Items().Size()); i++)
    {
        if (auto cbi = box.Items().GetAt(i).try_as<Controls::ComboBoxItem>())
        {
            if (winrt::to_string(cbi.Content().as<winrt::hstring>()) == text)
            {
                box.SelectedIndex(i);
                return;
            }
        }
    }
    box.SelectedIndex(0);
}

// ============================================================================
// XAML template implementations (normally generated by XAML compiler Pass2)
// ============================================================================
namespace winrt::Em68030::implementation
{
    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///Views/SettingsWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator);
        }
    }

    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::Connect(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        _contentLoaded = true;
    }

    template <typename D, typename... I>
    ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector
    SettingsWindowT<D, I...>::GetBindingConnector(int32_t /*connectionId*/, IInspectable const& /*target*/)
    {
        return nullptr;
    }

    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const&)
    {
        throw ::winrt::hresult_not_implemented();
    }

    template <typename D, typename... I>
    void SettingsWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
    }
}

namespace winrt::Em68030::implementation
{
    SettingsWindow::SettingsWindow()
    {
        InitializeComponent();

        // Populate named elements via FindName (ContentDialog is a FrameworkElement)
        BoardTypeBox(FindName(L"BoardTypeBox").try_as<Controls::ComboBox>());
        Mvme147Panel(FindName(L"Mvme147Panel").try_as<Controls::StackPanel>());
        // Mvme147RamBox removed — MemSizeBox is shared for all board types
        Mvme147RomBox(FindName(L"Mvme147RomBox").try_as<Controls::TextBox>());
        ScsiDiskListPanel(FindName(L"ScsiDiskListPanel").try_as<Controls::StackPanel>());
        NewScsiImageSizeBox(FindName(L"NewScsiImageSizeBox").try_as<Controls::TextBox>());
        ScsiCdromPathBox(FindName(L"ScsiCdromPathBox").try_as<Controls::TextBox>());
        ScsiCdromIdBox(FindName(L"ScsiCdromIdBox").try_as<Controls::ComboBox>());
        MemSizeBox(FindName(L"MemSizeBox").try_as<Controls::TextBox>());
        ConsoleEnabledBox(FindName(L"ConsoleEnabledBox").try_as<Controls::CheckBox>());
        ConsoleAddrBox(FindName(L"ConsoleAddrBox").try_as<Controls::TextBox>());
        ConsoleScrollbackBox(FindName(L"ConsoleScrollbackBox").try_as<Controls::TextBox>());
        ConsoleColumnsBox(FindName(L"ConsoleColumnsBox").try_as<Controls::TextBox>());
        ConsoleRowsBox(FindName(L"ConsoleRowsBox").try_as<Controls::TextBox>());
        HddEnabledBox(FindName(L"HddEnabledBox").try_as<Controls::CheckBox>());
        HddAddrBox(FindName(L"HddAddrBox").try_as<Controls::TextBox>());
        HddPathBox(FindName(L"HddPathBox").try_as<Controls::TextBox>());
        NewImageSizeBox(FindName(L"NewImageSizeBox").try_as<Controls::TextBox>());
        FontFamilyBox(FindName(L"FontFamilyBox").try_as<Controls::TextBox>());
        FontSizeBox(FindName(L"FontSizeBox").try_as<Controls::TextBox>());
        JitEnabledBox(FindName(L"JitEnabledBox").try_as<Controls::CheckBox>());
        JitMinBlockLengthBox(FindName(L"JitMinBlockLengthBox").try_as<Controls::TextBox>());
        JitCompileThresholdBox(FindName(L"JitCompileThresholdBox").try_as<Controls::TextBox>());
        EnableTraceButtonBox(FindName(L"EnableTraceButtonBox").try_as<Controls::CheckBox>());
        AddScsiDiskBtn(FindName(L"AddScsiDiskBtn").try_as<Controls::Button>());
        BootPartitionBox(FindName(L"BootPartitionBox").try_as<Controls::ComboBox>());
        TargetOSBox(FindName(L"TargetOSBox").try_as<Controls::ComboBox>());
        NetBsdPanel(FindName(L"NetBsdPanel").try_as<Controls::StackPanel>());
        LinuxPanel(FindName(L"LinuxPanel").try_as<Controls::StackPanel>());
        LinuxCommandLineBox(FindName(L"LinuxCommandLineBox").try_as<Controls::TextBox>());
        NetworkModeBox(FindName(L"NetworkModeBox").try_as<Controls::ComboBox>());
        NatGatewayIpBox(FindName(L"NatGatewayIpBox").try_as<Controls::TextBox>());
        NatGatewayMacBox(FindName(L"NatGatewayMacBox").try_as<Controls::TextBox>());
        TapAdapterBox(FindName(L"TapAdapterBox").try_as<Controls::ComboBox>());

        // Disable TAP mode item if no TAP adapters are installed
        m_tapAdapters = ::Em68030::IO::TapNetworkHandler::EnumerateAdapters();
        if (auto tapItem = FindName(L"TapModeItem").try_as<Controls::ComboBoxItem>())
            tapItem.IsEnabled(!m_tapAdapters.empty());
        // Populate TAP adapter list
        if (TapAdapterBox())
        {
            for (const auto& adapter : m_tapAdapters)
            {
                Controls::ComboBoxItem item;
                auto label = adapter.Name.empty() ? adapter.Description : adapter.Name;
                item.Content(winrt::box_value(winrt::to_hstring(label)));
                item.Tag(winrt::box_value(winrt::to_hstring(adapter.Guid)));
                TapAdapterBox().Items().Append(item);
            }
        }
        FramebufferEnabledBox(FindName(L"FramebufferEnabledBox").try_as<Controls::CheckBox>());
        FbResolutionBox(FindName(L"FbResolutionBox").try_as<Controls::ComboBox>());
        FbBppBox(FindName(L"FbBppBox").try_as<Controls::ComboBox>());

        // Wire event handlers programmatically (XAML Connect is no-op for C++ native)
        if (BoardTypeBox())
        {
            BoardTypeBox().SelectionChanged({ this, &SettingsWindow::BoardType_Changed });
        }
        if (auto btn = FindName(L"BrowseRomBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::BrowseRom_Click });
        if (auto btn = FindName(L"CreateScsiImageBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::CreateScsiImage_Click });
        if (auto btn = FindName(L"BrowseScsiCdromBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::BrowseScsiCdrom_Click });
        if (auto btn = FindName(L"BrowseHddBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::BrowseHdd_Click });
        if (auto btn = FindName(L"CreateHddImageBtn").try_as<Controls::Button>())
            btn.Click({ this, &SettingsWindow::CreateImage_Click });
        if (AddScsiDiskBtn())
        {
            AddScsiDiskBtn().Click([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                // Find first free SCSI ID
                std::set<int> usedIds;
                for (auto& row : m_diskRows)
                    usedIds.insert(GetSelectedScsiId(row.IdBox));
                usedIds.insert(GetSelectedScsiId(ScsiCdromIdBox()));
                int freeId = 0;
                for (int i = 0; i <= 6; i++) {
                    if (usedIds.find(i) == usedIds.end()) { freeId = i; break; }
                }
                AddDiskRow("", freeId);
                RefreshScsiIdOptions();
                UpdateTargetOSVisibility();
            });
        }
        if (TargetOSBox())
        {
            TargetOSBox().SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                UpdateTargetOSVisibility();
            });
        }
        if (ScsiCdromIdBox())
        {
            ScsiCdromIdBox().SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                if (!m_refreshingIds) RefreshScsiIdOptions();
            });
        }
        if (NetworkModeBox())
        {
            NetworkModeBox().SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
                UpdateNatGatewayEnabled();
            });
        }

        // --- Localize dialog ---
        Title(winrt::box_value(ResourceHelper::GetString(L"Window_Settings")));
        PrimaryButtonText(ResourceHelper::GetString(L"Dialog_OK"));
        CloseButtonText(ResourceHelper::GetString(L"Dialog_Cancel"));

        // Section headers
        if (auto tb = FindName(L"LblBoardType").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_BoardType"));
        if (auto tb = FindName(L"LblMvme147Settings").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Mvme147Settings"));
        if (auto tb = FindName(L"LblTargetOS").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_TargetOS"));
        if (auto tb = FindName(L"LblScsiDisks").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ScsiDisks"));
        if (auto tb = FindName(L"LblScsiDescription").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ScsiDescription"));
        if (auto tb = FindName(L"LblScsiCdRom").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ScsiCdRom"));
        if (auto tb = FindName(L"LblNetwork").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Network"));
        if (auto tb = FindName(L"LblMemory").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Memory"));
        if (auto tb = FindName(L"LblIoDevices").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_IoDevices"));
        if (auto tb = FindName(L"LblHddImage").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_HddImage"));
        if (auto tb = FindName(L"LblPerformance").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Performance"));
        if (auto tb = FindName(L"LblFramebuffer").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Framebuffer"));
        if (auto tb = FindName(L"LblDisplay").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Display"));

        // Field labels
        if (auto tb = FindName(L"LblBoard").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_Board"));
        if (auto tb = FindName(L"LblRomImage").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_RomImage"));
        if (auto tb = FindName(L"LblOperatingSystem").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_OperatingSystem"));
        if (auto tb = FindName(L"LblBootPartition").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_BootPartition"));
        if (auto tb = FindName(L"LblCommandLine").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_CommandLine"));
        if (auto tb = FindName(L"LblScsiNewImageSize").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_NewImageSizeMB"));
        if (auto tb = FindName(L"LblIsoImage").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_IsoImage"));
        if (auto tb = FindName(L"LblScsiCdromId").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ScsiId"));
        if (auto tb = FindName(L"LblNetworkMode").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_NetworkMode"));
        if (auto tb = FindName(L"LblNetworkDescription").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_NetworkDescription"));
        if (auto tb = FindName(L"LblGatewayIP").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_GatewayIP"));
        if (auto tb = FindName(L"LblGatewayMAC").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_GatewayMAC"));
        if (auto tb = FindName(L"LblMemorySizeMB").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_MemorySizeMB"));
        if (auto tb = FindName(L"LblMemoryDescription").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_MemoryDescription"));
        if (auto tb = FindName(L"LblConsoleBaseAddr").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ConsoleBaseAddr"));
        if (auto tb = FindName(L"LblScrollbackLines").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ScrollbackLines"));
        if (auto tb = FindName(L"LblTerminalSize").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_TerminalSize"));
        if (auto tb = FindName(L"LblHddBaseAddr").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_HddBaseAddr"));
        if (auto tb = FindName(L"LblImageFile").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_ImageFile"));
        if (auto tb = FindName(L"LblHddNewImageSize").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_NewImageSizeMB"));
        if (auto tb = FindName(L"LblMinBlockLength").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_MinBlockLength"));
        if (auto tb = FindName(L"LblCompileThreshold").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_CompileThreshold"));
        if (auto tb = FindName(L"LblFontFamily").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_FontFamily"));
        if (auto tb = FindName(L"LblFontSize").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_FontSize"));
        if (auto tb = FindName(L"LblJitDescription").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_JitDescription"));
        if (auto tb = FindName(L"LblFramebufferDescription").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_FramebufferDescription"));
        if (auto tb = FindName(L"LblFbResolution").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_FbResolution"));
        if (auto tb = FindName(L"LblFbBpp").try_as<Controls::TextBlock>())
            tb.Text(ResourceHelper::GetString(L"Settings_FbBpp"));

        // CheckBoxes
        if (ConsoleEnabledBox())
            ConsoleEnabledBox().Content(winrt::box_value(ResourceHelper::GetString(L"Settings_ConsoleEnabled")));
        if (HddEnabledBox())
            HddEnabledBox().Content(winrt::box_value(ResourceHelper::GetString(L"Settings_HddEnabled")));
        if (JitEnabledBox())
            JitEnabledBox().Content(winrt::box_value(ResourceHelper::GetString(L"Settings_EnableJit")));
        if (FramebufferEnabledBox())
            FramebufferEnabledBox().Content(winrt::box_value(ResourceHelper::GetString(L"Settings_EnableFramebuffer")));
        if (EnableTraceButtonBox())
            EnableTraceButtonBox().Content(winrt::box_value(ResourceHelper::GetString(L"Settings_EnableTraceButton")));

        // Set trace file path display
        if (auto lbl = FindName(L"LblTraceFilePath").try_as<Controls::TextBlock>())
        {
            auto tracePath = ::Em68030::Config::EmulatorConfig::GetDataDirectory() / "tracelog.txt";
            lbl.Text(winrt::hstring(L"Trace file: " + tracePath.wstring()));
        }

        // Buttons
        if (AddScsiDiskBtn())
            AddScsiDiskBtn().Content(winrt::box_value(ResourceHelper::GetString(L"Settings_AddDisk")));
        if (auto btn = FindName(L"CreateScsiImageBtn").try_as<Controls::Button>())
            btn.Content(winrt::box_value(ResourceHelper::GetString(L"Settings_Create")));
        if (auto btn = FindName(L"CreateHddImageBtn").try_as<Controls::Button>())
            btn.Content(winrt::box_value(ResourceHelper::GetString(L"Settings_Create")));

    }

    // ========================================================================
    // Dynamic SCSI disk row management
    // ========================================================================

    void SettingsWindow::AddDiskRow(const std::string& path, int scsiId)
    {
        DiskRowState row;
        row.DesiredId = scsiId;

        // ID label
        TextBlock idLabel;
        idLabel.Text(ResourceHelper::GetString(L"Settings_ScsiId"));
        idLabel.FontSize(13);
        idLabel.VerticalAlignment(VerticalAlignment::Center);
        idLabel.Margin(ThicknessHelper::FromLengths(0, 0, 4, 0));

        // ID ComboBox - items populated by RefreshScsiIdOptions
        ComboBox idBox;
        idBox.Width(70);
        idBox.VerticalAlignment(VerticalAlignment::Center);
        idBox.Margin(ThicknessHelper::FromLengths(0, 0, 4, 0));
        idBox.SelectionChanged([this]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            if (!m_refreshingIds) RefreshScsiIdOptions();
        });
        row.IdBox = idBox;

        // Path TextBox
        TextBox pathBox;
        pathBox.Text(winrt::to_hstring(path));
        pathBox.MinWidth(160);
        pathBox.FontFamily(Media::FontFamily(L"Consolas"));
        pathBox.VerticalAlignment(VerticalAlignment::Center);
        row.PathBox = pathBox;

        // Browse button
        Button browseBtn;
        browseBtn.Content(box_value(L"..."));
        browseBtn.Width(30);
        browseBtn.Margin(ThicknessHelper::FromLengths(4, 0, 0, 0));
        browseBtn.VerticalAlignment(VerticalAlignment::Center);
        size_t rowIndex = m_diskRows.size(); // capture current index
        browseBtn.Click([this, pathBox]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            BrowseFile(L"Disk Image", L".img", ResourceHelper::GetString(L"Settings_SelectScsiDisk"), pathBox);
        });
        row.BrowseBtn = browseBtn;

        // Remove button
        Button removeBtn;
        removeBtn.Content(box_value(L"\u00D7"));
        removeBtn.Width(36);
        removeBtn.Margin(ThicknessHelper::FromLengths(4, 0, 0, 0));
        removeBtn.VerticalAlignment(VerticalAlignment::Center);
        row.RemoveBtn = removeBtn;

        // Write NetBSD Disklabel button (enabled only when TargetOS is NetBSD)
        Button disklabelBtn;
        disklabelBtn.Content(box_value(ResourceHelper::GetString(L"Settings_Disklabel")));
        disklabelBtn.Margin(ThicknessHelper::FromLengths(4, 0, 0, 0));
        disklabelBtn.VerticalAlignment(VerticalAlignment::Center);
        disklabelBtn.FontSize(11);
        ToolTipService::SetToolTip(disklabelBtn,
            box_value(ResourceHelper::GetString(L"Settings_WriteDisklabel")));
        disklabelBtn.Click([this, pathBox]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            auto filePath = winrt::to_string(pathBox.Text());
            if (filePath.empty() || !std::filesystem::exists(filePath))
                return;
            auto confirmText = ResourceHelper::GetStdString(L"Settings_DisklabelConfirm");
            auto titleText = ResourceHelper::GetStdString(L"Settings_WriteDisklabel");
            auto result = MessageBoxW(GetOwnerHwnd(),
                confirmText.c_str(),
                titleText.c_str(), MB_OKCANCEL | MB_ICONQUESTION);
            if (result != IDOK) return;
            try {
                ::Em68030::IO::ScsiDisk::WriteNetBsdDisklabel(filePath);
            } catch (...) {}
        });
        row.DisklabelBtn = disklabelBtn;

        // Row grid (ensures TextBox fills remaining space, buttons always visible)
        Grid grid;
        grid.Margin(ThicknessHelper::FromLengths(0, 2, 0, 2));
        auto colAuto = Controls::ColumnDefinition();
        colAuto.Width(GridLengthHelper::Auto());
        auto colAuto2 = Controls::ColumnDefinition();
        colAuto2.Width(GridLengthHelper::Auto());
        auto colAuto3 = Controls::ColumnDefinition();
        colAuto3.Width(GridLengthHelper::Auto());
        auto colStar = Controls::ColumnDefinition();
        colStar.Width(GridLengthHelper::FromValueAndType(1, GridUnitType::Star));
        auto colAuto4 = Controls::ColumnDefinition();
        colAuto4.Width(GridLengthHelper::Auto());
        auto colAuto5 = Controls::ColumnDefinition();
        colAuto5.Width(GridLengthHelper::Auto());
        grid.ColumnDefinitions().Append(colAuto);
        grid.ColumnDefinitions().Append(colAuto2);
        grid.ColumnDefinitions().Append(colAuto3);
        grid.ColumnDefinitions().Append(colStar);
        grid.ColumnDefinitions().Append(colAuto4);
        grid.ColumnDefinitions().Append(colAuto5);
        Grid::SetColumn(idLabel, 0);
        Grid::SetColumn(idBox, 1);
        Grid::SetColumn(disklabelBtn, 2);
        Grid::SetColumn(pathBox, 3);
        Grid::SetColumn(browseBtn, 4);
        Grid::SetColumn(removeBtn, 5);
        grid.Children().Append(idLabel);
        grid.Children().Append(idBox);
        grid.Children().Append(disklabelBtn);
        grid.Children().Append(pathBox);
        grid.Children().Append(browseBtn);
        grid.Children().Append(removeBtn);
        row.RowPanel = grid;

        m_diskRows.push_back(row);

        // Wire remove button with captured index that finds row by grid identity
        removeBtn.Click([this, grid]([[maybe_unused]] auto const&, [[maybe_unused]] auto const&) {
            for (size_t i = 0; i < m_diskRows.size(); i++) {
                if (m_diskRows[i].RowPanel == grid) {
                    RemoveDiskRow(i);
                    break;
                }
            }
        });

        ScsiDiskListPanel().Children().Append(grid);
    }

    void SettingsWindow::RemoveDiskRow(size_t index)
    {
        if (index >= m_diskRows.size()) return;
        auto panel = m_diskRows[index].RowPanel;
        uint32_t idx = 0;
        if (ScsiDiskListPanel().Children().IndexOf(panel, idx))
            ScsiDiskListPanel().Children().RemoveAt(idx);
        m_diskRows.erase(m_diskRows.begin() + static_cast<ptrdiff_t>(index));
        RefreshScsiIdOptions();
    }

    int SettingsWindow::GetSelectedScsiId(const ComboBox& box) const
    {
        if (box && box.SelectedItem())
        {
            if (auto item = box.SelectedItem().try_as<ComboBoxItem>())
            {
                auto content = item.Content();
                if (content)
                {
                    try { return std::stoi(winrt::to_string(winrt::unbox_value<winrt::hstring>(content))); }
                    catch (...) {}
                }
            }
        }
        return 0;
    }

    void SettingsWindow::RefreshScsiIdOptions()
    {
        if (m_refreshingIds) return;
        m_refreshingIds = true;

        // Collect current IDs for each disk row
        std::vector<int> diskIds(m_diskRows.size());
        for (size_t i = 0; i < m_diskRows.size(); i++)
        {
            auto& row = m_diskRows[i];
            if (row.IdBox && row.IdBox.SelectedItem())
                diskIds[i] = GetSelectedScsiId(row.IdBox);
            else
                diskIds[i] = row.DesiredId;
        }

        int cdromId = (ScsiCdromIdBox() && ScsiCdromIdBox().SelectedItem())
                      ? GetSelectedScsiId(ScsiCdromIdBox())
                      : m_desiredCdromId;

        // Update each disk row's ComboBox
        for (size_t i = 0; i < m_diskRows.size(); i++)
        {
            auto& row = m_diskRows[i];
            int currentId = diskIds[i];

            std::set<int> otherIds;
            for (size_t j = 0; j < m_diskRows.size(); j++) {
                if (j != i) otherIds.insert(diskIds[j]);
            }
            otherIds.insert(cdromId);

            row.IdBox.Items().Clear();
            int selectIndex = 0;
            for (int id = 0; id <= 6; id++)
            {
                if (id != currentId && otherIds.find(id) != otherIds.end())
                    continue;
                ComboBoxItem item;
                item.Content(box_value(winrt::to_hstring(std::to_string(id))));
                row.IdBox.Items().Append(item);
                if (id == currentId)
                    selectIndex = static_cast<int>(row.IdBox.Items().Size()) - 1;
            }
            row.IdBox.SelectedIndex(selectIndex);
            row.DesiredId = currentId;
        }

        // Update CD-ROM ComboBox: exclude disk IDs
        if (ScsiCdromIdBox())
        {
            std::set<int> allDiskIds(diskIds.begin(), diskIds.end());
            int currentCdromId = cdromId;

            ScsiCdromIdBox().Items().Clear();
            int cdromSelectIndex = 0;
            for (int id = 0; id <= 6; id++)
            {
                if (id != currentCdromId && allDiskIds.find(id) != allDiskIds.end())
                    continue;
                ComboBoxItem item;
                item.Content(box_value(winrt::to_hstring(std::to_string(id))));
                ScsiCdromIdBox().Items().Append(item);
                if (id == currentCdromId)
                    cdromSelectIndex = static_cast<int>(ScsiCdromIdBox().Items().Size()) - 1;
            }
            ScsiCdromIdBox().SelectedIndex(cdromSelectIndex);
            m_desiredCdromId = currentCdromId;
        }

        // Update Add button: disable if all IDs taken
        if (AddScsiDiskBtn())
        {
            std::set<int> allUsed(diskIds.begin(), diskIds.end());
            allUsed.insert(cdromId);
            AddScsiDiskBtn().IsEnabled(allUsed.size() < 7);
        }

        m_refreshingIds = false;
    }

    // ========================================================================
    // LoadConfig / SaveConfig
    // ========================================================================

    void SettingsWindow::LoadConfig(const ::Em68030::Config::EmulatorConfig& config)
    {
        // Board type
        SelectItemByText(BoardTypeBox(), config.BoardType);
        Mvme147RomBox().Text(winrt::to_hstring(config.Mvme147RomPath));

        // SCSI Disks
        m_diskRows.clear();
        if (ScsiDiskListPanel())
            ScsiDiskListPanel().Children().Clear();
        for (const auto& disk : config.Mvme147ScsiDisks)
            AddDiskRow(disk.Path, disk.ScsiId);
        if (m_diskRows.empty())
            AddDiskRow("", 0);

        ScsiCdromPathBox().Text(winrt::to_hstring(config.Mvme147ScsiCdromPath));
        m_desiredCdromId = std::clamp(config.Mvme147ScsiCdromId, 0, 6);
        if (BootPartitionBox())
            BootPartitionBox().SelectedIndex(std::clamp(config.Mvme147BootPartition, 0, 1));
        if (TargetOSBox())
            SelectItemByText(TargetOSBox(), config.TargetOS);
        if (LinuxCommandLineBox())
            LinuxCommandLineBox().Text(winrt::to_hstring(config.LinuxCommandLine));
        UpdateTargetOSVisibility();
        if (NetworkModeBox())
            SelectItemByText(NetworkModeBox(), config.NetworkMode);
        if (NatGatewayIpBox())
            NatGatewayIpBox().Text(winrt::to_hstring(config.NatGatewayIp));
        if (NatGatewayMacBox())
            NatGatewayMacBox().Text(winrt::to_hstring(config.NatGatewayMac));
        // Select the saved TAP adapter by GUID
        if (TapAdapterBox() && !config.TapAdapterGuid.empty())
        {
            for (int i = 0; i < static_cast<int>(TapAdapterBox().Items().Size()); i++)
            {
                if (auto item = TapAdapterBox().Items().GetAt(i).try_as<Controls::ComboBoxItem>())
                {
                    auto tag = winrt::unbox_value_or<winrt::hstring>(item.Tag(), L"");
                    if (winrt::to_string(tag) == config.TapAdapterGuid)
                    {
                        TapAdapterBox().SelectedIndex(i);
                        break;
                    }
                }
            }
        }
        UpdateNatGatewayEnabled();
        UpdateMvme147Visibility();
        RefreshScsiIdOptions();

        // Memory
        MemSizeBox().Text(winrt::to_hstring(std::to_string(config.MemorySize / (1024 * 1024))));

        // I/O
        ConsoleEnabledBox().IsChecked(config.ConsoleEnabled);
        {
            wchar_t buf[16];
            swprintf_s(buf, L"%08X", config.ConsoleBaseAddress);
            ConsoleAddrBox().Text(buf);
        }
        ConsoleScrollbackBox().Text(winrt::to_hstring(std::to_string(config.ConsoleScrollbackLines)));
        if (ConsoleColumnsBox())
            ConsoleColumnsBox().Text(winrt::to_hstring(std::to_string(config.ConsoleColumns)));
        if (ConsoleRowsBox())
            ConsoleRowsBox().Text(winrt::to_hstring(std::to_string(config.ConsoleRows)));
        HddEnabledBox().IsChecked(config.HddEnabled);
        {
            wchar_t buf[16];
            swprintf_s(buf, L"%08X", config.HddBaseAddress);
            HddAddrBox().Text(buf);
        }
        HddPathBox().Text(winrt::to_hstring(config.HddImagePath));

        // Framebuffer
        if (FramebufferEnabledBox())
            FramebufferEnabledBox().IsChecked(config.FramebufferEnabled);
        if (FbResolutionBox())
        {
            struct Res { int w, h; };
            static constexpr Res presets[] = {
                {320,240},{640,480},{800,600},{1024,768},{1280,720},{1280,1024},{1920,1080}
            };
            int idx = 1; // default 640x480
            for (int i = 0; i < static_cast<int>(std::size(presets)); i++)
            {
                if (presets[i].w == config.FramebufferWidth && presets[i].h == config.FramebufferHeight)
                { idx = i; break; }
            }
            FbResolutionBox().SelectedIndex(idx);
        }
        if (FbBppBox())
        {
            int bppIndex = (config.FramebufferBpp == 8) ? 0 : (config.FramebufferBpp == 32) ? 2 : 1;
            FbBppBox().SelectedIndex(bppIndex);
        }

        // Performance
        if (JitEnabledBox())
            JitEnabledBox().IsChecked(config.JitEnabled);
        if (JitMinBlockLengthBox())
            JitMinBlockLengthBox().Text(winrt::to_hstring(std::to_string(config.JitMinBlockLength)));
        if (JitCompileThresholdBox())
            JitCompileThresholdBox().Text(winrt::to_hstring(std::to_string(config.JitCompileThreshold)));

        // Debug
        if (EnableTraceButtonBox())
            EnableTraceButtonBox().IsChecked(config.EnableTraceButton);

        // Display
        FontFamilyBox().Text(winrt::to_hstring(config.FontFamily));
        FontSizeBox().Text(winrt::to_hstring(std::to_string(config.FontSize)));
    }

    bool SettingsWindow::SaveConfig(::Em68030::Config::EmulatorConfig& config)
    {
        // Board type
        config.BoardType = GetSelectedItemText(BoardTypeBox());

        config.Mvme147RomPath = winrt::to_string(Mvme147RomBox().Text());

        // SCSI Disks
        config.Mvme147ScsiDisks.clear();
        for (auto& row : m_diskRows)
        {
            std::string path = winrt::to_string(row.PathBox.Text());
            int id = GetSelectedScsiId(row.IdBox);
            if (!path.empty())
                config.Mvme147ScsiDisks.push_back({ path, id });
        }

        config.Mvme147ScsiCdromPath = winrt::to_string(ScsiCdromPathBox().Text());
        config.Mvme147ScsiCdromId = GetSelectedScsiId(ScsiCdromIdBox());
        if (BootPartitionBox())
            config.Mvme147BootPartition = BootPartitionBox().SelectedIndex();
        if (TargetOSBox())
            config.TargetOS = GetSelectedItemText(TargetOSBox());
        if (LinuxCommandLineBox())
            config.LinuxCommandLine = winrt::to_string(LinuxCommandLineBox().Text());
        if (NetworkModeBox())
            config.NetworkMode = GetSelectedItemText(NetworkModeBox());
        if (NatGatewayIpBox())
        {
            auto ip = winrt::to_string(NatGatewayIpBox().Text());
            // Validate: ParseIpAddress returns default on invalid input
            auto parsed = ::Em68030::IO::SlirpNetworkHandler::ParseIpAddress(ip);
            config.NatGatewayIp = std::to_string(parsed[0]) + "." + std::to_string(parsed[1]) + "." +
                                  std::to_string(parsed[2]) + "." + std::to_string(parsed[3]);
        }
        if (NatGatewayMacBox())
        {
            auto mac = winrt::to_string(NatGatewayMacBox().Text());
            auto parsed = ::Em68030::IO::SlirpNetworkHandler::ParseMacAddress(mac);
            char buf[18];
            snprintf(buf, sizeof(buf), "%02x:%02x:%02x:%02x:%02x:%02x",
                     parsed[0], parsed[1], parsed[2], parsed[3], parsed[4], parsed[5]);
            config.NatGatewayMac = buf;
        }
        if (TapAdapterBox() && TapAdapterBox().SelectedItem())
        {
            if (auto item = TapAdapterBox().SelectedItem().try_as<Controls::ComboBoxItem>())
            {
                auto tag = winrt::unbox_value_or<winrt::hstring>(item.Tag(), L"");
                config.TapAdapterGuid = winrt::to_string(tag);
            }
        }

        // Memory size
        auto memText = winrt::to_string(MemSizeBox().Text());
        try {
            int memMB = std::clamp(std::stoi(memText), 4, 4096);
            config.MemorySize = memMB * 1024 * 1024;
        }
        catch (...) { /* keep previous */ }

        // I/O
        config.ConsoleEnabled = ConsoleEnabledBox().IsChecked().Value();
        auto conAddrText = winrt::to_string(ConsoleAddrBox().Text());
        try { config.ConsoleBaseAddress = static_cast<uint32_t>(std::stoul(conAddrText, nullptr, 16)); }
        catch (...) { /* keep previous */ }

        auto scrollbackText = winrt::to_string(ConsoleScrollbackBox().Text());
        try { config.ConsoleScrollbackLines = std::clamp(std::stoi(scrollbackText), 0, 100000); }
        catch (...) { /* keep previous */ }

        if (ConsoleColumnsBox())
        {
            try { config.ConsoleColumns = std::clamp(std::stoi(winrt::to_string(ConsoleColumnsBox().Text())), 80, 320); }
            catch (...) { /* keep previous */ }
        }
        if (ConsoleRowsBox())
        {
            try { config.ConsoleRows = std::clamp(std::stoi(winrt::to_string(ConsoleRowsBox().Text())), 24, 80); }
            catch (...) { /* keep previous */ }
        }

        config.HddEnabled = HddEnabledBox().IsChecked().Value();
        auto hddAddrText = winrt::to_string(HddAddrBox().Text());
        try { config.HddBaseAddress = static_cast<uint32_t>(std::stoul(hddAddrText, nullptr, 16)); }
        catch (...) { /* keep previous */ }

        config.HddImagePath = winrt::to_string(HddPathBox().Text());

        // Framebuffer
        if (FramebufferEnabledBox())
            config.FramebufferEnabled = FramebufferEnabledBox().IsChecked().Value();
        if (FbResolutionBox())
        {
            struct Res { int w, h; };
            static constexpr Res presets[] = {
                {320,240},{640,480},{800,600},{1024,768},{1280,720},{1280,1024},{1920,1080}
            };
            int idx = FbResolutionBox().SelectedIndex();
            if (idx >= 0 && idx < static_cast<int>(std::size(presets)))
            {
                config.FramebufferWidth = presets[idx].w;
                config.FramebufferHeight = presets[idx].h;
            }
        }
        if (FbBppBox())
        {
            auto bppText = GetSelectedItemText(FbBppBox());
            try { config.FramebufferBpp = std::stoi(bppText); }
            catch (...) { /* keep previous */ }
        }

        // Performance
        if (JitEnabledBox())
            config.JitEnabled = JitEnabledBox().IsChecked().Value();
        if (JitMinBlockLengthBox())
        {
            try { config.JitMinBlockLength = std::clamp(std::stoi(winrt::to_string(JitMinBlockLengthBox().Text())), 1, 64); }
            catch (...) { /* keep previous */ }
        }
        if (JitCompileThresholdBox())
        {
            try { config.JitCompileThreshold = std::clamp(std::stoi(winrt::to_string(JitCompileThresholdBox().Text())), 1, 255); }
            catch (...) { /* keep previous */ }
        }

        // Debug
        if (EnableTraceButtonBox())
            config.EnableTraceButton = EnableTraceButtonBox().IsChecked().Value();

        config.FontFamily = winrt::to_string(FontFamilyBox().Text());

        auto fontSizeText = winrt::to_string(FontSizeBox().Text());
        try { config.FontSize = std::stod(fontSizeText); }
        catch (...) { /* keep previous */ }

        // Validate: framebuffer enabled requires enough RAM for kernel (min 32MB usable)
        if (config.FramebufferEnabled)
        {
            constexpr uint32_t MIN_KERNEL_RAM = 32u * 1024 * 1024; // 32MB
            uint32_t vramBase = config.ComputeVramBase();
            if (vramBase < MIN_KERNEL_RAM)
            {
                uint32_t vramSize = static_cast<uint32_t>(config.FramebufferWidth)
                    * config.FramebufferHeight * config.FramebufferBpp / 8;
                int requiredMB = static_cast<int>((MIN_KERNEL_RAM + vramSize + 0xFFFFF) / (1024 * 1024));
                config.MemorySize = requiredMB * 1024 * 1024;
                MemSizeBox().Text(winrt::to_hstring(std::to_string(requiredMB)));
            }
        }

        return true;
    }

    // Recursively walk the visual tree to find a named element
    static DependencyObject FindChildByName(DependencyObject const& parent, hstring const& name)
    {
        int count = Media::VisualTreeHelper::GetChildrenCount(parent);
        for (int i = 0; i < count; i++)
        {
            auto child = Media::VisualTreeHelper::GetChild(parent, i);
            if (auto fe = child.try_as<FrameworkElement>())
            {
                if (fe.Name() == name)
                    return child;
            }
            auto result = FindChildByName(child, name);
            if (result != nullptr)
                return result;
        }
        return nullptr;
    }

    IAsyncOperation<ContentDialogResult> SettingsWindow::ShowAsync(UIElement const& parent)
    {
        this->XamlRoot(parent.XamlRoot());
        auto dialog = this->try_as<ContentDialog>();

        // Override the dialog's internal MaxWidth via the BackgroundElement in the template
        constexpr double dialogWidth = 640.0;
        auto openedToken = dialog.Opened([dialogWidth](ContentDialog const& sender, ContentDialogOpenedEventArgs const&) {
            auto bgElement = FindChildByName(sender, L"BackgroundElement");
            if (auto border = bgElement.try_as<Controls::Border>())
            {
                border.MaxWidth(dialogWidth);
                border.MinWidth(dialogWidth);
            }
            auto layoutRoot = FindChildByName(sender, L"LayoutRoot");
            if (auto grid = layoutRoot.try_as<Controls::Grid>())
            {
                grid.MaxWidth(dialogWidth);
            }
            // Disable the ContentDialog's internal ScrollViewer so that our
            // explicit ScrollViewer receives mouse wheel events directly.
            auto csvElement = FindChildByName(sender, L"ContentScrollViewer");
            if (auto csv = csvElement.try_as<Controls::ScrollViewer>())
            {
                csv.VerticalScrollMode(Controls::ScrollMode::Disabled);
                csv.VerticalScrollBarVisibility(Controls::ScrollBarVisibility::Disabled);
            }
        });

        auto result = co_await dialog.ShowAsync();
        dialog.Opened(openedToken);
        co_return result;
    }

    // ========================================================================
    // MVME147 panel visibility
    // ========================================================================

    void SettingsWindow::UpdateMvme147Visibility()
    {
        bool isMvme = GetSelectedItemText(BoardTypeBox()) == "MVME147";
        if (auto tab = FindName(L"TabMvme147").try_as<Controls::PivotItem>())
            tab.IsEnabled(isMvme);
    }

    void SettingsWindow::UpdateTargetOSVisibility()
    {
        bool isLinux = GetSelectedItemText(TargetOSBox()) == "Linux";
        if (NetBsdPanel())
            NetBsdPanel().Visibility(isLinux ? Visibility::Collapsed : Visibility::Visible);
        if (LinuxPanel())
            LinuxPanel().Visibility(isLinux ? Visibility::Visible : Visibility::Collapsed);

        // Disklabel buttons are only useful for NetBSD disk images
        for (auto& row : m_diskRows)
        {
            if (row.DisklabelBtn)
            {
                row.DisklabelBtn.IsEnabled(!isLinux);
                row.DisklabelBtn.Opacity(isLinux ? 0.35 : 1.0);
            }
        }
    }

    void SettingsWindow::UpdateNatGatewayEnabled()
    {
        auto mode = GetSelectedItemText(NetworkModeBox());
        bool isNat = mode.find("NAT") != std::string::npos;
        bool isTap = mode.find("TAP") != std::string::npos;
        if (NatGatewayIpBox())
        {
            NatGatewayIpBox().IsEnabled(isNat);
            NatGatewayIpBox().Opacity(isNat ? 1.0 : 0.35);
        }
        if (NatGatewayMacBox())
        {
            NatGatewayMacBox().IsEnabled(isNat);
            NatGatewayMacBox().Opacity(isNat ? 1.0 : 0.35);
        }
        if (TapAdapterBox())
        {
            TapAdapterBox().IsEnabled(isTap);
            TapAdapterBox().Opacity(isTap ? 1.0 : 0.35);
        }
    }

    void SettingsWindow::BoardType_Changed([[maybe_unused]] IInspectable const& sender,
                                           [[maybe_unused]] SelectionChangedEventArgs const& e)
    {
        // Guard against calls during initialization before XAML elements exist
        if (Mvme147Panel())
        {
            UpdateMvme147Visibility();
        }
    }

    // ========================================================================
    // File browser helpers
    // ========================================================================

    HWND SettingsWindow::GetOwnerHwnd() const
    {
        // ContentDialog does not have its own HWND. We need to find the
        // parent Window's HWND via the XamlRoot. In practice, the caller
        // must set XamlRoot before calling ShowAsync, and we walk to find
        // the Window.
        // For file pickers in ContentDialog context, we use the foreground window.
        return ::GetActiveWindow();
    }

    winrt::fire_and_forget SettingsWindow::BrowseFile(winrt::hstring filterName, winrt::hstring filterExt,
                                                       winrt::hstring title,
                                                       TextBox targetBox)
    {
        FileOpenPicker picker;
        picker.as<::IInitializeWithWindow>()->Initialize(GetOwnerHwnd());
        picker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
        picker.FileTypeFilter().Append(filterExt);
        picker.FileTypeFilter().Append(L"*");

        auto file = co_await picker.PickSingleFileAsync();
        if (file != nullptr)
        {
            targetBox.Text(file.Path());
        }
    }

    winrt::fire_and_forget SettingsWindow::SaveFile(winrt::hstring filterName, winrt::hstring filterExt,
                                                     winrt::hstring title,
                                                     TextBox targetBox,
                                                     bool isScsiDisk)
    {
        // Unmount currently mounted disks so the file is not locked
        if (isScsiDisk && m_unmountScsiDisks)
            m_unmountScsiDisks();

        FileSavePicker picker;
        picker.as<::IInitializeWithWindow>()->Initialize(GetOwnerHwnd());
        picker.SuggestedStartLocation(PickerLocationId::DocumentsLibrary);
        picker.FileTypeChoices().Insert(filterName, single_threaded_vector<hstring>({ filterExt }));
        picker.SuggestedFileName(L"disk.img");

        auto file = co_await picker.PickSaveFileAsync();
        if (file == nullptr) co_return;

        auto filePath = winrt::to_string(file.Path());

        int sizeMB = 0;
        try
        {
            if (isScsiDisk)
                sizeMB = std::stoi(winrt::to_string(NewScsiImageSizeBox().Text()));
            else
                sizeMB = std::stoi(winrt::to_string(NewImageSizeBox().Text()));
        }
        catch (...) { co_return; }

        if (sizeMB <= 0) co_return;
        sizeMB = std::clamp(sizeMB, 100, 2097152);

        long long sizeBytes = static_cast<long long>(sizeMB) * 1024 * 1024;

        // Create the image file
        if (isScsiDisk)
        {
            // Create empty file of the requested size
            {
                std::ofstream ofs(filePath, std::ios::binary);
                if (ofs)
                {
                    ofs.seekp(sizeBytes - 1);
                    ofs.put('\0');
                }
            }
            // Write NetBSD disklabel if TargetOS is NetBSD
            bool isNetBsd = GetSelectedItemText(TargetOSBox()) != "Linux";
            if (isNetBsd)
                ::Em68030::IO::ScsiDisk::WriteNetBsdDisklabel(filePath);
        }
        else
        {
            ::Em68030::IO::HddDevice::CreateImage(filePath, sizeBytes);
        }

        targetBox.Text(file.Path());
    }

    // ========================================================================
    // Browse button handlers
    // ========================================================================

    void SettingsWindow::BrowseRom_Click([[maybe_unused]] IInspectable const& sender,
                                         [[maybe_unused]] RoutedEventArgs const& e)
    {
        BrowseFile(L"ROM Image", L".bin", ResourceHelper::GetString(L"Settings_SelectRomImage"), Mvme147RomBox());
    }

    void SettingsWindow::BrowseHdd_Click([[maybe_unused]] IInspectable const& sender,
                                         [[maybe_unused]] RoutedEventArgs const& e)
    {
        BrowseFile(L"HDD Image", L".img", ResourceHelper::GetString(L"Settings_SelectHddImage"), HddPathBox());
    }

    void SettingsWindow::BrowseScsiCdrom_Click([[maybe_unused]] IInspectable const& sender,
                                               [[maybe_unused]] RoutedEventArgs const& e)
    {
        BrowseFile(L"ISO Image", L".iso", ResourceHelper::GetString(L"Settings_SelectCdRomIso"), ScsiCdromPathBox());
    }

    // ========================================================================
    // Create image handlers
    // ========================================================================

    void SettingsWindow::CreateScsiImage_Click([[maybe_unused]] IInspectable const& sender,
                                               [[maybe_unused]] RoutedEventArgs const& e)
    {
        // Find or create a target TextBox - use the first empty disk row, or create a new one
        TextBox targetBox{ nullptr };
        for (auto& row : m_diskRows) {
            if (row.PathBox && row.PathBox.Text().empty()) {
                targetBox = row.PathBox;
                break;
            }
        }
        if (!targetBox) {
            AddDiskRow("", 0);
            RefreshScsiIdOptions();
            targetBox = m_diskRows.back().PathBox;
        }
        SaveFile(L"Disk Image", L".img", ResourceHelper::GetString(L"Settings_CreateScsiDisk"), targetBox, true);
    }

    void SettingsWindow::CreateImage_Click([[maybe_unused]] IInspectable const& sender,
                                           [[maybe_unused]] RoutedEventArgs const& e)
    {
        SaveFile(L"HDD Image", L".img", ResourceHelper::GetString(L"Settings_CreateHddImage"), HddPathBox(), false);
    }
}
